### PR TITLE
[FIX] newpct - Login problem

### PR DESCRIPTION
**Pull request by rsalas**
### Config usage if relevant (new plugin or updated schema):
```
    rss:
      url: http://feeds2.feedburner.com/newpctorrent
    form:
      url: http://www.newpct.com/entrar/
      userfield: userName
      passfield: userPass
      username: '{? newpct.user ?}'
      password: '{? newpct.pass ?}'

```
### Log and/or tests output (preferably both):
```
CRITICAL task          newpct    BUG: Unhandled error in plugin form: expected name token at '<!<31?106:(132,0x0))'
CRITICAL manager       newpct    An unexpected crash has occurred. Writing crash report to /home/rsalas/.flexget/crash_report.2017.05.29.114147849135.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.55
WARNING  task          newpct    Aborting task (plugin: form)
```

### CODE REVIEW

**Comment by cvium** [comment]
@rsalas Python 3 is most likely broken because of this commit https://github.com/Flexget/Flexget/commit/fe59a6a772811f8685422088b69d1f790abd8094, in other words, not related to your changes.

**Comment by liiight** [comment]
Remerge from develop now

**Comment by liiight** [comment]
This is ready and working, right?

**Comment by javichu666** [comment]
New version 2.10.58 has the same problem

2017-06-04 17:34 CRITICAL task          series_sigo     BUG: Unhandled error in plugin form: expected name token at '<!<31?106:(132,0x0))'
2017-06-04 17:34 CRITICAL manager       series_sigo     An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2017.06.04.173440184212.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.58

**Comment by cvium** [comment]
What do you mean new version? This is a pull request that hasn't been merged.

**Comment by javichu666** [comment]
Ok thanks. Now is merged. With develop version 2.10.60.dev it works right

Thanks you very much for your help.

**Comment by malkavi** [comment]
I think that this can be closed without merging. This is fixed with PR #1838 .

**Comment by liiight** [comment]
Right

**Comment by rsalas** [comment]
Sorry, but the bug not is fixed...

I'm use:
flexget -V
2.10.65
You are on the latest release.

2017-06-27 09:04 CRITICAL manager       seriesnewpct    An unexpected crash has occurred. Writing crash report to ~/.flexget/crash_report.2017.06.27.090413460355.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.65
2017-06-27 09:04 WARNING  task          seriesnewpct    Aborting task (plugin: form)

**crash_report.2017.06.27.090413460355.log**
2017-06-27 09:04 CRITICAL task          seriesnewpct    BUG: Unhandled error in plugin form: expected name token at '<!<31?106:(132,0x0))'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/operate/formlogin.py", line 77, in on_task_start
    for form in br.forms():
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 420, in forms
    return self._factory.forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 557, in forms
    self._forms_factory.forms())
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 237, in forms
    _urlunparse=_rfc3986.urlunsplit,
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 844, in ParseResponseEx
    _urlunparse=_urlunparse,
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 981, in _ParseFileEx
    fp.feed(data)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 760, in feed
    raise ParseError(exc)
ParseError: expected name token at '<!<31?106:(132,0x0))'

**Comment by malkavi** [comment]
Can you paster your config? I'm using newpct feed without any error:
`rss:
  url: http://www.newpct.com/feed/
  link: link`
Do you have this error in every run?

**Comment by rsalas** [comment]
The config file is this:
`
tasks:
  seriesnewpct:
    rss:
      url: http://feeds2.feedburner.com/newpctorrent
      link: link
    form:
      url: http://www.newpct.com/entrar/
      userfield: userName
      passfield: userPass
      username: 'newpct.user'
      password: 'newpct.pass'
    priority: 2
    metainfo_series: yes
`

If you change you config for this and try, the script crash.
No need a valid user/pass with this configuration you can check.

**Comment by malkavi** [comment]
But why are you login to newpct? You can download from newpct without login.

**Comment by rsalas** [comment]
I'm not use login in newpct, but if anyone use this fix solve the problem.
And is for all forms, if html is malformed don't crash.

**Comment by malkavi** [comment]
Ok. But then this isn't a fix for newpct, maybe you have to change the title to something more general like "prevent malformed login forms".

**Comment by rsalas** [comment]
Yes, but the problem is detected in newpct login form. I'm fixed the problem and others forms, too. :)

**Pull request closed without merging**
