### PR TITLE
parallel docker platform builds

### PR DESCRIPTION
**Pull request by ksurl**
### Motivation for changes:

speed up docker build workflow

### Detailed changes:
- use matrix for multi runner builds

### Addressed issues/feature requests:
- Fixes # .

### Config usage if relevant (new plugin or updated schema):
```
paste_config_here
```
### Log and/or tests output (preferably both):
```
paste output here
```
#### To Do:

- [ ] Stuff..

### CODE REVIEW

**Comment by gazpachoking** [comment]
Hmm. Seems like a good idea. Is it just coincidence that this build took longer than all the previous ones though?

**Comment by ksurl** [comment]
> Hmm. Seems like a good idea. Is it just coincidence that this build took longer than all the previous ones though?

Maybe since they are all separate now, there was no previous cache?

**Comment by ksurl** [comment]
Oh it's not merged yet so it wouldn't be any faster i dont think

**Comment by ksurl** [comment]
My test repo has issues pushing the image (only pushes arm, not amd64), so this needs some debugging before it can be merged.

**Comment by ksurl** [comment]
I can't figure it out, but the sha doesn't match with independent platform builds so, I think we'll have to abandon this for now. 7-8min for the build is not bad anyways. I was working on another project where builds were 3 hours.

**Pull request closed without merging**
