### PR TITLE
npo_watchlist: Rewrite to support new npo.nl layout

### LINKED ISSUE #1892: BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
latest version of flexget and download-npo installed.

config.yml
```yaml
tasks:
tv-journaal:
npo_watchlist:
email: xxx
password: yyy
remove_accepted: yes
max_episode_age_days: 7
accept_all: yes
exec:
fail_entries: yes
auto_escape: yes
on_output:
for_accepted:
- /usr/local/bin/download-npo -o "/var/storage/queue/tvshows/NPO/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel} ({episode_id})" -t {{url}}
```
```
2017-07-05 20:31 CRITICAL task tv-journaal BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
return method(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 326, in on_task_input
entries += self._get_favorites_entries(task, config)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 318, in _get_favorites_entries
series_info = self._get_series_info(task, config, series_name, url)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 180, in _get_series_info
series_info['npo_url'] = tvseries.find('a', itemprop='url')['href']
AttributeError: 'NoneType' object has no attribute 'find'
```
Something changed on the NPO site?

### LINKED ISSUE #1893: npo.nl site is overhauled and has new account system
This is a reminder to myself to update the npo_watchlist plugin for the new npo.nl account system for flexget.

I don't have time atm but will look into it asap

### PR DESCRIPTION
**Pull request by jeroenl**
Known issue: removing watchlist entries sometimes results in a 500 error, would appreciate any suggestions.

Closes #1892 and closes #1893.

### CODE REVIEW

**Comment by jeroenl** [comment]
I don't know how to update the cassette. @mfonville, can you help?

**Comment by liiight** [comment]
Delete them and rerun tests

**Comment by jeroenl** [comment]
Ok, as npo.nl seems to have deleted all accounts (my personal account was also gone), I can't run these tests. @mfonville, do you know what the set up of this account was?

**Comment by mfonville** [comment]
npo.nl has introduced indeed a new account system, so we have to re-create an account with a throw-away email address.

In the old test-account (and what would be most easy to do again for the new account) was that I had added "Zondag met Lubach" and "Als de dijken breken" as favorite series

**Comment by mfonville** [comment]
I have re-created now a new test-account, I will try to see if I can fix the tests for you

**Comment by liiight** [comment]
Closed due to #1907

**Comment by jeroenl** [comment]
Thanks, @mfonville!

**Pull request closed without merging**
