### PR TITLE
Lower loglevels of movie-queue IMDB/TMDB lookup fails to Debug, avoiding logspam.

### PR DESCRIPTION
**Pull request by antivirtel**
I'd like to avoid logspams like this:
```
2016-04-02 12:27 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for SomeShow 720p
2016-04-02 12:27 INFO     imdb_lookup   nC_movie-HUN    Title `someshow 720p` lookup failed
```

### CODE REVIEW

**Comment by liiight** [comment]
I don't agree with this, I think warning is the relevant level for a failed lookup. 
Movie queue itself is due for depreciation in the near future so I wouldn't even bother with that anyway.

**Comment by antivirtel** [comment]
Look at my current log:
```
2016-04-02 20:12 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Joy.Ride.3.2014.720p.BluRay.x264.DTS.HUN-N&R
2016-04-02 20:12 INFO     imdb_lookup   nC_movie-HUN    Title `joy.ride.3.2014.720p.bluray.x264.dts.hun-n&r` lookup failed
2016-04-02 20:28 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for joy.ride.3.2014.720p.bluray.x264.dts.hun-n&r
2016-04-02 21:16 CRITICAL plugin        nC_movie-HUN    Unable to download the RSS for task nC_movie-HUN (https://ncore.cc/rss/rssdd.xml): ('Connection aborted.', BadStatusLine("''",))
2016-04-02 21:16 WARNING  task          nC_movie-HUN    Aborting task (plugin: rss)
2016-04-02 21:32 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Edwin.Boyd.2011.720p.BluRay.x264.DTS.HUN-N&R
2016-04-02 21:32 INFO     imdb_lookup   nC_movie-HUN    Title `edwin.boyd.2011.720p.bluray.x264.dts.hun-n&r` lookup failed
2016-04-02 21:48 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for edwin.boyd.2011.720p.bluray.x264.dts.hun-n&r
2016-04-02 22:51 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Marokkó
2016-04-02 22:52 INFO     imdb_lookup   nC_movie-HUN    Title `marokkó` lookup failed
2016-04-02 22:52 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Montana.Sky.2007
2016-04-02 22:52 INFO     imdb_lookup   nC_movie-HUN    Title `montana.sky.2007` lookup failed
2016-04-02 23:08 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for marokkó
2016-04-02 23:08 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for montana.sky.2007
2016-04-02 23:40 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Észak és Dél 3. rész
2016-04-02 23:40 INFO     imdb_lookup   nC_movie-HUN    Title `észak és dél 3. rész` lookup failed
2016-04-02 23:40 WARNING  imdb_lookup   nC_movie-HUN    IMDB lookup failed for Észak és Dél 2. rész
2016-04-02 23:40 INFO     imdb_lookup   nC_movie-HUN    Title `észak és dél 2. rész` lookup failed
2016-04-02 23:55 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for észak és dél 3. rész
2016-04-02 23:55 INFO     imdb_lookup   nC_movie-HUN    Imdb lookup failed for észak és dél 2. rész
```

What do you think, which line is the only line I care about?
This: `2016-04-02 21:16 CRITICAL plugin        nC_movie-HUN    Unable to download the RSS for task nC_movie-HUN (https://ncore.cc/rss/rssdd.xml): ('Connection aborted.', BadStatusLine("''",))`

This movie-queue plugin spams the same errors, since I've configured with @gazpachoking first...
```
templates:
  dwn:
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.passwd }}'
      main_file_only: yes
      include_subs: yes
    set:
      addpaused: yes
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: '{{title}}'
      body: '⬇{{ rss_pubdate|formatdate("%H:%M:%S %a, %d.") }} {{task}}'
      url: '{{url}}'

  nC_rss:
    rss:
      url: https://ncore.cc/rss/rssdd.xml
    headers:
      Cookie: "nick={{ secrets.ncore.nick }}; pass={{ secrets.ncore.pass }}"

tasks:
nC_movie-HUN:
    template:
      - dwn
      - nC_rss
    assume_quality:
      any: 480p sdtv
    regexp:
      reject_excluding:
        - Film \(HUN:
            from: category
      reject:
        - xvid
    manipulate:
      - category:
          from: title
          extract: '.* (\[.*\])'
      - title:
          from: title
          extract: '(.*) \[.*\]'
    movie_queue: accept
```

That's why, these should be VERBOSE log messages, but unfortunately, I didn't find that loglevel in code, IDK why...

**Comment by cvium** [comment]
Maybe https://github.com/tarzasai/.flexget/blob/master/plugins/log_filter.py better suits your needs.

**Comment by liiight** [comment]
Movie queue is deprecated

**Pull request closed without merging**
