### PR TITLE
rTorrent output plugin

### PR DESCRIPTION
**Pull request by RSully**
This is a WIP branch of an rTorrent output plugin. 

Example config:

```yaml
rtorrent:
  uri: 'scgi://localhost:5000'
  directory: '/path/default_dest/'
  custom1: '/path/{{ series_name }}'
```

### CODE REVIEW

**Comment by stevezau** [comment]
RScully,

I was also working on a RTorrent Plugin. See pull request https://github.com/Flexget/Flexget/pull/495

Perhaps we should work on it together?

**Comment by crawln45** [comment]
So is it working yet.

**Comment by RSully** [comment]
The plugin works, but does not yet start torrents automatically. It isn't that this functionality is difficult, I just want to make sure it is implemented the correct way so I've been putting it off. It is the very next thing on my todo list.

@stevezau kind of a weird coincidence that the day I decide to finally write this (after months of putting it off) is the same time someone else does too; if only I had put it off for another week I probably wouldn't have had to write this at all. But, it's a little late for me to throw in the towel now. Feel free to take a look at my code and add your input, I'd love the collaboration!

**Comment by stevezau** [comment]
@RSully Yeah it is, i saw you mention it on the IRC channel but you had left before I could let you know i was working on one as well.

anyway, no point working on two different code bases, lets discuss on the IRC channel and merge?

**Comment by stevezau** [comment]
@RSully FYI: Currently http(s) and a local socket are not supported. I suggest you support both of these as SCGI insecure compare to http/local.

Pyrobase appears to support both http(s) and local socket in the master branch on github https://github.com/pyroscope/pyrobase/tree/master/src/pyrobase/io

For some reason pypi for pyrocore is not up-to-date. I created a ticket here https://github.com/pyroscope/pyrobase/issues/2

**Comment by stevezau** [comment]
@RSully check my latest commit. Still needs to be refined but it's functional

**Comment by RSully** [comment]
Woah, lots of changes in 1 commit. Will take a bit to fully absorb. 

I did go ahead and revert a couple things though; specifically you reverted from using the new RPC commands to the old ones, and stuff like directory vs path seem weird and add complexity. Hope that is alright!

This latest commit is untested, and I am a little confused about error handling with your new classes. I'll be on IRC for a while and will try to figure it out tonight.

**Comment by stevezau** [comment]
@gazpachoking code is ready for review..

I can't change WIP title as it's owned by @RSully

**Comment by gazpachoking** [comment]
Lot to review, especially since I don't know anything about rtorrent. Cursory glance seems good though. @RSully @stevezau If you guys both think it's ready I'll merge.

**Comment by stevezau** [comment]
@gazpachoking im happy for it to be merged

**Comment by cvium** [comment]
@stevezau @RSully Does this allow functionality such as Deluge's `movedone`?

**Comment by stevezau** [comment]
@cvium possibly, what the use case and ill let you know to do it?

**Comment by cvium** [comment]
@stevezau Right now I have 2 tasks. One downloads and lets Deluge know where to place finished downloads (eg. move to /some/staging/area/{{series_name}}) via `movedone` setting.
The 2nd task deletes garbage and moves the video files to a final location where Kodi picks them up.

What has kept me from using rTorrent is that it lacks the `movedone` option.

**Comment by paranoidi** [comment]
rTorrent can move completed stuff though. I think we just need to set correct options somehow. This PR is looking quite awesome, rarely I have seen such well written and tested PRs :)

**Comment by RSully** [comment]
You can emulate `movedone` by setting a custom field and then a completion handler in rtorrent's config to move the file and change the directory.

**Comment by cvium** [comment]
I'm well aware that rTorrent is very complex and offers a huge variety of customizations, but I'm much too lazy to read up on it. I just want something simple to set up :stuck_out_tongue:

**Comment by stevezau** [comment]
@cvium rTorrent can auto move on complete via the rtorrent config.. take a look at http://flexget.com/wiki/Cookbook/rTorrent

You can do something similar with this plugin.

tasks:
  TV:
    accept_all: yes
    rtorrent:
      uri: scgi://localhost:5000
      start: yes
      path: /downloads/tv

  TV-MOVE:
    from_rtorrent:
      uri: scgi://localhost:5000
      path: /data/incoming/tv
    regexp:
      accept_excluding:
        - complete
      from: custom1
    rtorrent:
      action: update
      uri: scgi://localhost:5000
      path: /data/TVShows
      custom1: complete

**Comment by stevezau** [comment]
@paranoidi lol... using mock to write the tests was actually pretty cool.. i plan on using it alot more.. starting on the new ui next.

**Comment by cvium** [comment]
@stevezau Is it possible to implement magnets? I know the ruTorrent supports them.

**Comment by cvium** [comment]
@stevezau @RSully I've been toying around with rTorrent this afternoon and it doesn't seem to be working properly in 0.9.4/0.13.4.

It gives the error `Command on torrent creation failed: Junk at end of input.` whenever the field `custom1` (and any other field I guess) contains whitespace eg.:

```
rtorrent:
      uri: scgi://localhost:5000
      start: yes
      path: '/downloads/'
      custom1: '/staging/tv/{{ tvdb_series_name }}'
```
where `tvdb_series_name` is some tv show name containing whitespace.

**Comment by stevezau** [comment]
@cvium i don't think magnets will work at this stage.. To be honest i know nothing about magnets but i think it's fairly easy to support..

can you create a ticket for your issue with the plugin and magnet support?

let me know the ticket urls

**Comment by stevezau** [comment]
@cvium a quick test shows the same error on mine, i think i have to escape spaces.. will fix this and create another pull request.

**Comment by stevezau** [comment]
@cvium I believe i've fixed the issue.. It's waiting to be merged from pull request https://github.com/Flexget/Flexget/pull/519

**Comment by cvium** [comment]
@stevezau I have created a ticket http://flexget.com/ticket/3014.

**Comment by stevezau** [comment]
@cvium ok sure, I've never used magnets before so i'll have to have a look.. Fairly sure i can just copy how the other plugins do it.

Also i've created a page on the wiki with info on this plugin http://flexget.com/wiki/Plugins/rtorrent

**Pull request merged**
