### PR TITLE
Update morethantv categories

### PR DESCRIPTION
**Pull request by spgomez**
Categories were obsolete. Updated to reflect the current six categories.

Morethantv plugin was not working correctly

### Detailed changes:
removed previous categories : TV, Movies, Other
added new categories: HD Episode, HD Movies, HD Season, SD Episode, SD Movies, SD Season

### CODE REVIEW

**Comment by gazpachoking** [comment]
My only concern is that people's configs will break (not pass validation.) I guess they were a bit broken anyway without this, but not sure how we should handle. Maybe we just bump the version and add an upgrade action.

**Comment by spgomez** [comment]
I couldn't get it working with the current category settings. Seems like MoreThanTv changed things when they re-launch. I'd be interested to see if anyone currently has the plugin working. 

I'm currenting using a filtered RSS feed and it's working just fine, so I'd understand if this wasn't something you felt like messing with.

Thanks for the feedback.

**Comment by gazpachoking** [comment]
Merged in 2711281c177fd665f9dfe1d60521ba716fcfb7dd

**Comment by gazpachoking** [comment]
Updated the wiki page and UpgradeActions page to mention the new categories.

**Pull request closed without merging**
