### PR TITLE
Fix subtitles subliminal http://flexget.com/ticket/3061

### PR DESCRIPTION
**Pull request by camon**

### CODE REVIEW

**Comment by camon** [comment]
Failed checks why?!

**Comment by gazpachoking** [comment]
> Failed checks why?!

Guessit (one of our deps) dropped 2.6 support. We need to update some of our requirements to fix that. Probably nothing to do with your changes.

**Comment by camon** [comment]
@gazpachoking ok thanks

**Comment by gazpachoking** [comment]
Thanks!

**Pull request merged**
