### PR TITLE
Fix crash when using convert_magnets with aria2

### LINKED ISSUE #1604: Crash when using convert_magnet with aria2.
There is a crash when using convert_magnet with aria2.

```
2017-01-02 19:51 CRITICAL task          discover_movies_hd BUG: Unhandled error in plugin aria2: u'file'
2017-01-02 19:51 CRITICAL manager       discover_movies_hd An unexpected crash has occurred. Writing crash report to /home/wyrm/.flexget/crash_report.2017.01.02.195150778857.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.8.17.dev
2017-01-02 19:51 WARNING  task          discover_movies_hd Aborting task (plugin: aria2)

```
I don't have a crashlog, sorry.

### PR DESCRIPTION
**Pull request by drwyrm**
Fixes #1604

### CODE REVIEW

**Comment by liiight** [comment]
I don't see how that could cause a crash. Try to get the crash log for the issue

**Comment by drwyrm** [comment]
I deleted it, sorry.

It crashes on line 115, there is no entry['file'] being set by convert_magnet, ref. line 95 of plugins/modify/convert_magnet.py .

**Comment by drwyrm** [comment]
Hum... thinking better, this doesn't look like a proper fix.

The entry passed content_filter, so convert_magnet worked. The entry has entry['torrent'], but for some reason there is no entry['file'].

The fix is wrong because the .torrent file never gets uploaded to aria2, but it works anyway, because in this case it will just add the url itself to aria2, which will download metadata again and start the download anyway.

Proper fix would need me to figure why there is no entry['file'] for this entry, when there is entry['torrent']..

Here is a bit more log context:
```
2017-01-02 19:51 INFO     urlrewriter   discover_movies_hd Entry 'Only Yesterday (1991) 720p BrRip x264 Pimp4003 (PimpRG)' URL rewritten to magnet:?xt=urn:btih:ed2a2ec2d1b52a
ec72f2526272a3581dc3424a37&dn=Only+Yesterday+%281991%29+720p+BrRip+x264+Pimp4003+%28PimpRG%29&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A
1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969 (with piratebay)
2017-01-02 19:51 INFO     convert_magnet discover_movies_hd Converting entry Only Yesterday (1991) 720p BrRip x264 Pimp4003 (PimpRG) magnet URI to a torrent file
2017-01-02 19:51 INFO     download      discover_movies_hd Downloading: Only Yesterday (1991) 720p BrRip x264 Pimp4003 (PimpRG)
2017-01-02 19:51 VERBOSE  details       discover_movies_hd Summary - Accepted: 1 (Rejected: 140 Undecided: 35 Failed: 0)
2017-01-02 19:51 INFO     aria2         discover_movies_hd Connecting to daemon at http://xxxxxx:xxxxxx@192.168.1.96:6800/rpc
2017-01-02 19:51 CRITICAL task          discover_movies_hd BUG: Unhandled error in plugin aria2: u'file'
2017-01-02 19:51 CRITICAL manager       discover_movies_hd An unexpected crash has occurred. Writing crash report to /home/wyrm/.flexget/crash_report.2017.01.02.195150778857.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.8.17.dev

```

**Comment by drwyrm** [comment]
Ignore this noise. The problem here was that there was another, conflicting version of convert_magnet.py being used.

`
2017-01-02 19:30 CRITICAL plugin                        Error while registering plugin convert_magnet. A plugin with the same name is already registered
`

Worst is that mine, unmerged version of convert_magnet.py works... and current version doesn't, like in #1514 .

**Pull request closed without merging**
