### PR TITLE
TVMaze: Normalise show queries with dots.

### PR DESCRIPTION
**Pull request by planeturban**
### Motivation for changes:

tvmaze returns 404 when searching for series names with dots instead of spaces. When using filesystem as config for series *NIX users (most probably) uses dots instead of spaces in series names ("american.dad" vs "american dad"), and there are (probably) a very few series in tvmaze's database that's entered with the dot it ought to be better to just normalise the query format.

`manipulate` is of no use in this case since it can't (I couldn't at least) replace the dots in the `tv-series` template below. 

### Detailed changes:
- added a replace('.' ' ') for title.

### Config usage if relevant (new plugin or updated schema):

Condensed, removed outputs, this is for reproducing bug. 

```yaml
templates:
 rarbg-search:
    set:
      search_string: "{{ name | replace('.', ' ') }}"
    discover:
#      interval: "3 hours"
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - rarbg:
            category: 41
            min_seeders: 5
  tv-series:
    plugin_priority:
      manipulate: 10
    exists_series:
      - /mnt/tv-archive/{{series_name|replace(' ','.')|replace("_", ".")}}
      - /downloads/torrents/tv
    configure_series:
      settings:
        identified_by: ep
        tracking: backfill
        qualities:
          - 720p+
      from:
        filesystem:
          path:
            - /mnt/tv-archive
tasks:
  rarbg:
    priority: 10
    domain_delay:
      torrentapi.org: 5 seconds
    set:
      path: /mnt/tv-archive/{{series_name|replace(' ','.')|replace("_", ".")|lower}}/s{{series_season|pad(2)}}
    verify_ssl_certificates: no
    template:
      - tv-series
      - rarbg-search

```

### Log and/or tests output (preferably both):
Tests run: 
* Backfill search, no 404 when using "american.dad" as input.

### CODE REVIEW

**Comment by liiight** [comment]
The problem here is not with TVMaze, is that the series parser does not normalize the name. This is an entirely different issue. 

I'm closing this, please open an issue.

**Comment by planeturban** [comment]
Yeah, I can see how that’s the case from my tests with manipulate.

So the are some other options in this case:

1. Adding regexp to configure_series. 

2. Adding another phase to manipulate. 

Right?

**Comment by BrutuZ** [comment]
3- 
```yaml
set:
  series_name: {{series_name|replace('.',' ')
```

**Comment by planeturban** [comment]
> 3-
> 
> ```yaml
> set:
>   series_name: {{series_name|replace('.',' ')}}
> ```

No dice, tried both in `tv-series` and `rarbg-search` templates.

````
1316458-2020-05-20 09:02:27 DEBUG    api_tvmaze    rarbg           searching lookup table using title star.trek.picard                                                                                                                                                                                              
1316569-2020-05-20 09:02:27 DEBUG    api_tvmaze    rarbg           trying to fetch series star.trek.picard from tvmaze                                                                                                                                                                                              
1316680:2020-05-20 09:02:27 DEBUG    api_tvmaze    rarbg           querying tvmaze API with the following URL: https://api.tvmaze.com/singlesearch/shows                                                                                                                                                            
1316825:2020-05-20 09:02:27 DEBUG    utils.requests rarbg           GETing URL https://api.tvmaze.com/singlesearch/shows with args () and kwargs {'params': {'embed': 'seasons', 'q': 'star.trek.picard'}, 'allow_redirects': True, 'timeout': 30}                                                                  
1317060:2020-05-20 09:02:27 DEBUG    est_series_tvmaze rarbg           404 Client Error: Not Found for url: https://api.tvmaze.com/singlesearch/shows?embed=seasons&q=star.trek.picard                                                                                                                              
1317235-2020-05-20 09:02:27 DEBUG    est_movies    rarbg           Unable to check release for star.trek.picard S02E01, tmdb_release and movie_year fields are not defined                                                                                                                                          
1317398-2020-05-20 09:02:27 DEBUG    discover      rarbg           No release date could be determined for star.trek.picard S02E01                                                                                                 

````

**Comment by liiight** [comment]
This won't work since estimators run before `set` plugin.
@gazpachoking there's something weird here. It looks like the name is being normalized correctly, but `series.name` returns the original name and not the normalized one, as (i think) it should.

**Comment by planeturban** [comment]
Don’t think it’s a matter of estimators since it’s the filter data itself we’re trying to modify.

**Comment by planeturban** [comment]
I'm paging doctor @gazpachoking for some consultation. :) 

I kinda forgot about this one. But I think it needs some TLC..

**Pull request closed without merging**
