### PR TITLE
Reorder Quality plugin

### PR DESCRIPTION
**Pull request by cvium**
### Motivation for changes:
Sometimes I disagree with quality priorities for some sites. With this plugin I can change the ordering.

### Detailed changes:

- Added plugin and one test to make sure it sets value at task start and restores original value at task exit/abort

### Config usage if relevant (new plugin or updated schema):
```
reorder_quality:
  webrip:
    above: hdtv
```

### CODE REVIEW

**Comment by liiight** [comment]
Thus requires knowing the value for each quality component, doesn't it? That's not very user friendly imo

**Comment by cvium** [comment]
Same can be said for plugin_priority

**Comment by liiight** [comment]
yep, i agree. That one sucks too. Doesn't mean we should perpetuate it.

**Comment by cvium** [comment]
Going to reopen against develop later.

**Comment by grr** [comment]
> Thus requires knowing the value for each quality component, doesn't it? That's not very user friendly imo

couldn't manipulate plugin be used to swap the qualities to accomplish the same thing? i.e. if hdtv is found, replace with webrip, and vice versa.

**Comment by liiight** [comment]
This plugin doesn't manipulate entry quality, it enables overriding the hard coded quality component values to create custom comparisons.

**Pull request merged**
