### PR TITLE
RTorrent plugin bug fixes

### PR DESCRIPTION
**Pull request by stevezau**
-Fix bug with renaming to a folder with spaces
-Fix bug with spaces in customX fields on load
-Fix bug with spaces in path

### CODE REVIEW

**Comment by cvium** [comment]
Cool. Thanks.

**Comment by stevezau** [comment]
@cvium thanks. Are you on the IRC channel? What's your nick? I'd love to get some feedback.

**Comment by cvium** [comment]
@stevezau I've never really used IRC since the 90s, but I can make an appearance. Same nick.

**Comment by stevezau** [comment]
@cvium it's ok.. not needed.

Anyway, I haven't fully fixed the bug on moving torrents to another directory.. I'll open another PR when i fully test and fix it.

**Comment by cvium** [comment]
@stevezau Well, I'm on IRC anyway :stuck_out_tongue:

**Pull request merged**
