### PR TITLE
Convert Magnet plugin

### PR DESCRIPTION
**Pull request by nikdoof**
This plugin uses libtorrent to convert a magnet URI torrent to a full torrent file by spinning up a small torrent client to pull from the DHT. This way magnets from non-torrent file sites can be processed using the content filters. 

Obviously the conversion is time consuming and in situations its possible for invalid torrents to take a lot of time to actually acquire the metadata, a parameter has been added to time out any long hanging queries.

This iteration has been running on my personal machine for a long period of time, suggestions are welcome.

### CODE REVIEW

**Comment by cvium** [comment]
I think it looks interesting and seems like a decent way of not relying on torcache and what have you.

Have there been any particularly annoying problems?

**Comment by nikdoof** [comment]
By far the biggest one is invalid torrents which don't exist in the DHT swarm which run the full timeout, hence why I added the configurable timeout. Generally it takes around 3-5sec to acquire a highly shared torrent, which most of the time will be connecting to the DHT in the first place. 

I'm sure some further configuration options could be added for the mini-client itself, but the defaults work well for direct connections and simple UPnP firewall setups.

**Comment by cvium** [comment]
From what I gather this plugin will always rewrite magnet urls unless specifically disabled?

**Comment by nikdoof** [comment]
Ahh yes, looks that way. I'm checking for ```config == False``` but the default config setup is enabling it. This isn't the intended result, i'll make changes to resolve it.

**Pull request closed without merging**
