### PR TITLE
Added headers for newznab, re-added 'wait' as per documentation.

### PR DESCRIPTION
**Pull request by planeturban**

### CODE REVIEW

**Comment by gazpachoking** [comment]
Can we use requests instead of urllib2?

**Comment by planeturban** [comment]
I'll look in to it, but there should be no problem since we're just getting data to be processed with FeedParser.

I'll change 'wait' from integer to string, interval as well.

**Comment by gazpachoking** [comment]
If we use `task.requests` it means this plugin will respect other request modifying plugins like `headers`

**Comment by liiight** [comment]
@planeturban you wanna change this so i'll merge?

**Comment by liiight** [comment]
Reopen if relevant

**Comment by planeturban** [comment]
*doh* Too much at the office.. Will fix soon. ;)

**Pull request merged**
