### PR TITLE
Remove webui v1

### PR DESCRIPTION
**Pull request by kristenmills**
### Motivation for changes:
Web UI v2 has parity so no longer necessary to run them side by side

### Detailed changes:
- Remove webui v1 code
- Remove logic to build webui v1
- Move webui to run at root instead of /v2
- Add logging that the run_v2 is no longer necessary in config

### Log and/or tests output (preferably both):
```
web_server: yes
tasks: []
```
```
2020-01-03 23:13:50 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2020-01-03 23:13:50 INFO     web_server_daemon                 Initiating API
2020-01-03 23:13:50 INFO     web_server_daemon                 Registering WebUI
2020-01-03 23:13:50 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
2020-01-03 23:13:50 INFO     scheduler                     Starting scheduler
2020-01-03 23:13:50 INFO     web_server                    Web interface available at http://192.168.86.244:5050
```
```
web_server: 
  run_v2: yes
tasks: []
```
```
2020-01-03 23:14:29 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2020-01-03 23:14:29 INFO     web_server_daemon                 Initiating API
2020-01-03 23:14:29 WARNING  web_server_daemon                 run_v2: true is redundant and can be removed
2020-01-03 23:14:29 INFO     web_server_daemon                 Registering WebUI
2020-01-03 23:14:29 INFO     web_server                    Web interface available at http://192.168.86.244:5050
2020-01-03 23:14:29 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
2020-01-03 23:14:29 INFO     scheduler                     Starting scheduler
```
#### To Do:

- [ ] Update relevant wiki stuff

### CODE REVIEW

**Comment by stevezau** [comment]
Looks ok to me. @kristenmills i cannot remember, is v2 included in the flexget build?

**Comment by liiight** [comment]
I dont see the rush in deprecating v1 honestly. Without any usage data we dont know who uses any part of it so I'm not sure we should rush to remove it so soon honestly. There are still a number of missing view at this time (logs, execute, config editor, status, seen and history) and unless me make an implicit decision that they are redundant or ay least they some of then are, I think removing v1 can wait.

**Comment by kristenmills** [comment]
@stevezau yes it is.

After discussion in chat yesterday, I think i'm going to put web ui v2 at root and make web_ui 1 opt in instead of deprecating right away.

**Comment by kristenmills** [comment]
will do it in a new PR

**Pull request closed without merging**
