### PR TITLE
Encoding of path when content_filename is set

### PR DESCRIPTION
**Pull request by Bop4yN**
Attempt to fix ticket http://flexget.com/ticket/2824

### CODE REVIEW

**Comment by gazpachoking** [comment]
Hmm, shouldn't that already be happening here? https://github.com/Flexget/Flexget/blob/develop/flexget/utils/titles/series.py#L20

**Comment by Bop4yN** [comment]
Not sure how the loglevel can affect the problem. 
In any case, the latest update of series.py was October 27, and the problem is still there.

**Comment by gazpachoking** [comment]
Man, that is not at all the line I meant to link. This is where I meant:
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/plugin_transmission.py#L326

**Comment by Bop4yN** [comment]
That's more like it.:)
I think so too. Moreover, I have already written about it in http://flexget.com/ticket/2824
But somehow download_dir breaks in the line 492
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/plugin_transmission.py#L492
From error log:
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py", line 487, in add_to_transmission
        file_path = os.path.dirname(os.path.join(download_dir, fl[r.id][main_id]['name']))

**Comment by Bop4yN** [comment]
Hmmm... may be here is the problem
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/plugin_transmission.py#L438

And must be
fl = cli.get_files(r.id).encode('utf-8')
isn't it?

**Comment by stevezau** [comment]
hey @Bop4yN  I assume this is still a problem?? can you describe the problem again with fresh logs and ill take a look? I am not clear on what the actual issue is and the cause.

**Comment by gazpachoking** [comment]
This isn't quite the right fix. If somebody has more details please open up a new Github issue.

**Pull request closed without merging**
