### PR TITLE
Update t411 api to https

### PR DESCRIPTION
**Pull request by poulpito**
T411 modify api to respond only to https (http fallback to https)
without modification the api cannot retrieve json

### CODE REVIEW

**Comment by karma007** [comment]
Hello, version 1.15.30, I have this error : 

2017-04-11 14:16 DEBUG    t411_api      get_tvshowshd_411 None API token. Authenticating with "xxxxxx" account...
2017-04-11 14:16 DEBUG    utils.requests get_tvshowshd_411 Fetching URL https://api.t411.ai/auth with args () and kwargs {'json': None, 'data': {u'username': u'xxxxxx', u'password': u'pppppppp'}, u'timeout': 30}
2017-04-11 14:16 DEBUG    plugin        get_tvshowshd_411 decorator caught ValueError. handled traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/t411.py", line 75, in on_task_input
    return proxy.search(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 663, in search
    json_results = self.rest_client.search(client_query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 168, in wrapper
    self.auth()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 211, in auth
    json_response = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-04-11 14:16 CRITICAL plugin        get_tvshowshd_411 Expecting value: line 1 column 1 (char 0)
2017-04-11 14:16 WARNING  task          get_tvshowshd_411 Aborting task (plugin: t411)
2017-04-11 14:16 DEBUG    notify_entry  get_tvshowshd_411 sending abort notification

thanks

**Comment by cvium** [comment]
Please stop cluttering issues and PRs that are not at all related to that bug...

**Comment by karma007** [comment]
Sorry cvium, but why is it not related to this domain name recent change ?
(i'm not a developer sorry)

**Comment by cvium** [comment]
There is an open issue... https://github.com/Flexget/Flexget/issues/1783

**Pull request merged**
