### PR TITLE
search_cpasbien modified to use cloudflare-scrape

### PR DESCRIPTION
**Pull request by xfouloux**
As cpasbien switched to cloudflare, I had to modify the code.
So now, you have to have https://github.com/Anorov/cloudflare-scrape and all it's dependency to make it work.
Also, the file cfscrape.py must be put in the folder : /var/lib/flexget

But won't work until the download plugin use scrape too.

### CODE REVIEW

**Comment by gazpachoking** [comment]
> But won't work until the download plugin use scrape too.

I think that library works as a requests adapter. What we could do is make a cloudflare plugin, which when included in a task installed the cloudflare-scrape adapter on the task.requests session. Then the plugin doesn't have any tie to search_cpasbien, and could be used in the config for any site.

I guess we'd also want a way so that if a plugin that requires it was used, (like search_cpasbien,) it was automatically enabled.

**Comment by stevezau** [comment]
@gazpachoking I agree this could be layered over requests..

@xfouloux have you made any progress on this?

**Comment by xfouloux** [comment]
@stevezau I know that https://github.com/Anorov/cloudflare-scrape is now installable with PIP so it is better than before.

@gazpachoking I agree totally but my skills are limited in python, and I would not be able to do this.

**Comment by cvium** [comment]
I have already made a cloudflare scrape plugin. Can be enabled in a task with "cfscraper: yes".

**Comment by stevezau** [comment]
Closing as the same functionality is available via http://flexget.com/wiki/Plugins/cfscraper

**Comment by cvium** [comment]
Should probably update the wiki so people know that cfscraper must be enabled.

**Pull request closed without merging**
