### PR TITLE
Fix tvmaze api calls

### LINKED ISSUE #1724: tvmaze_lookup fails as URL changed
Based on the problem description here:
https://discuss.flexget.com/t/tvmaze-lookup-defect-notify-entries-telegram/3250

### Expected behaviour:
tvmaze information like URL, or poster is cached and can be used for notifications

### Actual behaviour:
the link is not working, as the URL / value in the string has been changed

this is since 25.02, 23 o'clock

### Steps to reproduce:
- Step 1: ...

#### Config:
```
 [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
 [Show page]({{tvmaze_series_url|replace("_", "%5F")}})
```
  
#### Log:
```
2017-03-08 18:25 DEBUG    api_tvmaze    get_favtvshowshd querying tvmaze API with the following URL: http://api.tvmaze.com/lookup/shows
2017-03-08 18:25 DEBUG    utils.requests get_favtvshowshd Fetching URL http://api.tvmaze.com/lookup/shows with args () and kwargs {u'allow_redirects': True, 'params': {u'thetvdb_id': 304196}, u'timeout':
2017-03-08 18:25 DEBUG    tvmaze_lookup get_favtvshowshd 400 Client Error: Bad Request for url: http://api.tvmaze.com/lookup/shows?thetvdb_id=304196
2017-03-08 18:25 DEBUG    api_tvmaze    get_favtvshowshd returning search params for series lookup: {u'tvdb_id': 304196, u'tvmaze_id': None, u'name': u'The Path', u'tvrage_id': None}
2017-03-08 18:25 DEBUG    api_tvmaze    get_favtvshowshd searching db tvmaze_series for the values [(u'tvdb_id', 304196), (u'tvmaze_id', None), (u'name', u'The Path'), (u'tvrage_id', None)]
2017-03-08 18:25 DEBUG    api_tvmaze    get_favtvshowshd trying to fetch series The Path from tvmaze
2017-03-08 18:25 DEBUG    api_tvmaze    get_favtvshowshd querying tvmaze API with the following URL: http://api.tvmaze.com/lookup/shows
2017-03-08 18:25 DEBUG    utils.requests get_favtvshowshd Fetching URL http://api.tvmaze.com/lookup/shows with args () and kwargs {u'allow_redirects': True, 'params': {u'thetvdb_id': 304196}, u'timeout':
2017-03-08 18:25 DEBUG    tvmaze_lookup get_favtvshowshd 400 Client Error: Bad Request for url: http://api.tvmaze.com/lookup/shows?thetvdb_id=304196
2017-03-08 18:25 DEBUG    api_tvdb      get_favtvshowshd Looking up tvdb information for The Path 304196
2017-03-08 18:25 DEBUG    api_tvdb      get_favtvshowshd Series <name=The Path,tvdb_id=304196> information restored from cache.
```

### Additional information:

It looks like the tvmaze API URL changed

from
http://api.tvmaze.com/lookup/shows?thetvdb_id=304196

to
http://api.tvmaze.com/lookup/shows?thetvdb=304196

The link is without the "_id" string...

Info from the TVMAZE API website:
http://imgur.com/ykzhLfz

### PR DESCRIPTION
**Pull request by haarts**
### Motivation for changes:
The TVMaze API recently started offering an HTTPS endpoint.
Flexget used the wrong query parameters when looking up series on the TVMaze API.
 
### Detailed changes:

- Changed the `BASE_URL`.
- Removed the `_id` suffixes.

### Addressed issues:

- Fixes #1724. 

### Log and/or tests output (preferably both):

I'll be needing some help here. I'm not sure how to test this properly.

### CODE REVIEW

**Comment by liiight** [comment]
You need to recreate the cassettes. Delete all relevant ones from from the cassettes folder under tests and run all tvmaze tests again

**Comment by haarts** [comment]
@liiight I'd like to solicit your guidance on this final failing error. It must be something silly. The [error message](https://travis-ci.org/Flexget/Flexget/jobs/210669904#L426) seems pretty evident but I can't dive deep enough to to figure out this schema error. 
To be frank I think it has something to do with the last commit https://github.com/Flexget/Flexget/pull/1727/commits/d791a6b3e52c5fdf6ad9923283253e647185e0a3, looking at that diff I see much less Tvmaze API calls than previously.

**Comment by liiight** [comment]
Hmm, I'll look into that,hopefully tomorrow.

**Comment by haarts** [comment]
@liiight The commit I flagged was indeed the culprit. I think something went wrong with my connection during recording. 
The good news is the tests are all green!

**Comment by liiight** [comment]
Thanks!

**Pull request merged**
