### PR TITLE
[parser] Movie titles parsing improvements

### PR DESCRIPTION
**Pull request by drwyrm**

### CODE REVIEW

**Comment by drwyrm** [comment]
Please notice that I can't update the imdb cassette because the "Taken" test fails from my IP without the geolocation nuke from my other Pull Request.

**Comment by liiight** [comment]
you wanna sync this?

**Comment by drwyrm** [comment]
Sorry for the delay, was out of town and without access to my github account.

@liiight Yes, would be nice. Been using it for a while on my production flexget, improved title parsing considerably.

@paranoidi PR for that commit is here, real+final special case and better year parsing for movies that contains years in the title.

**Comment by paranoidi** [comment]
Looks good to me

**Pull request merged**
