### PR TITLE
Update python-telegram-bot from v12.8 to v21.9

### PR DESCRIPTION
**Pull request by vivodi**
### Motivation for changes:
1. Update python-telegram-bot from v12.8 to v21.9, closing #4076
2. Add an option to use chat_id in telegram bot notifier, closing #4055

Related PR needs to be merged: https://github.com/Flexget/wiki/pull/16 (doc)

### CODE REVIEW

**Comment by vivodi** [comment]
@gazpachoking This is ready for review.

**Comment by gazpachoking** [comment]
LGTM. I suppose we should bump the minor version and add an upgrade action since users of this plugin will need to upgrade the library with this version

**Comment by gazpachoking** [comment]
Thanks!

**Comment by vivodi** [comment]
> After this I need to install package `python-telegram-bot`, even though I don't use telegram. Is it expected?
> 
> Log

May be fixed by #4088

**Pull request merged**
