### PR TITLE
Supported TV series entries and date stripping in anidb_list

### PR DESCRIPTION
**Pull request by radek-sprta**
As title says, added some functionality to anidb_list plugin.

### CODE REVIEW

**Comment by liiight** [comment]
Is it possible to add a default to the config so that users current config won't break while maintaining current behavior?

**Comment by radek-sprta** [comment]
Thanks for pointing that out. Should be compatible with current config now.

**Comment by liiight** [comment]
Thanks. Can you update the wiki please?

**Comment by radek-sprta** [comment]
Done.

**Comment by liiight** [comment]
:+1:

**Pull request merged**
