### PR TITLE
fromseason position

### PR DESCRIPTION
**Pull request by douggutaby**
With this feature the plugin can look for all of the episodes of the season you watch.
For example if you start a new TV show with fromseason config it won't only search one episode of the season but all of them.

I created it in 2017 and totally forget it. Today I upgraded flexget to python3 and I rewrite the plugin again.

### CODE REVIEW

**Comment by BrutuZ** [comment]
How would this differ from something like setting the `series`' `begin` with `trakt_list` and then `discover`'s `next_series_episode`?

**Comment by douggutaby** [comment]
> How would this differ from something like setting the `series`' `begin` with `trakt_list` and then `discover`'s `next_series_episode`?

I don't really undestand yours. Can you show me an example config? Maybe it is an existing feature but I used the plugin wrong :)

**Comment by BrutuZ** [comment]
**Loosely** something like that (snipped from my current config, tried to keep the relevant lines).
```yaml
tasks:
  fill-series-episode-list:
    priority: 1
    trakt_list:
      account: "{? trakt.account ?}"
      list: "{? trakt.series ?}"
      type: episodes
      strip_dates: yes
    accept_all: yes
    set_series_begin: yes
    list_remove:
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.series ?}"
          type: episodes
    list_add:
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.series ?}"
          type: shows
  download-series-discover:
    priority: 2
    discover:
      release_estimations: strict
      interval: 1 hour
      what:
        - next_series_episodes:
            from_start: yes
      from:
        ...
```
With this I can add an episode to the list, the first task sets that episode as the `series`' `begin` episode and replaces the episode with the show on the Trakt list.
The second task will look for episodes from the configured `begin` until it's up-to-date.

**Comment by douggutaby** [comment]
Does it stop at the end of the season or continue with the next one?

**Comment by BrutuZ** [comment]
> until it's up-to-date
... or you remove the show from the list, I guess xD

Maybe something could be done replacing `type: episodes` with `type: seasons`, but the season parsing from `trakt_list` seems to be broken right now =/

https://github.com/Flexget/Flexget/blob/develop/flexget/components/trakt/trakt_list.py#L248

**Comment by douggutaby** [comment]
TBH I didn’t look for a solution. I just saw I can solve my problem with this plugin and a I did. If you think it is not needed or already there in others just delete my request. :)

**Comment by BrutuZ** [comment]
Apologies if I sounded dismissive in any way, wasn't my intention. Was just trying to understand the use-case, that's why I asked if that config would achieve the same you're trying to, how much more complicated it is if so, etc...

I'm just a user like yourself, I don't have any authority or even saying on what gets merged or not, was just genuinely curious 🙂

**Comment by douggutaby** [comment]
Oh man, don’t worry, you’re right. The use case is that I want to download a full season but only the season I watch.
I will try your config in the morning. It’s 0:05 here :)

**Comment by douggutaby** [comment]
I'm not sure I'm understand how your config is working but with my solution this is what it tries to download:

> 2020-03-14 09:13:04 VERBOSE  discover      discover-shows  Family Guy S18E15 hasn't been released yet (Expected: 2020-03-15 00:00:00)
> 2020-03-14 09:13:06 VERBOSE  discover      discover-shows  The Walking Dead S10E12 hasn't been released yet (Expected: 2020-03-15 00:00:00)
> 2020-03-14 09:13:06 VERBOSE  discover      discover-shows  Supernatural S15E12 hasn't been released yet (Expected: 2020-03-16 00:00:00)
> 2020-03-14 09:13:06 VERBOSE  discover      discover-shows  Modern Family S11E15 hasn't been released yet (Expected: 2020-03-18 00:00:00)
> 2020-03-14 09:13:10 VERBOSE  discover      discover-shows  Avenue 5 S01E09 hasn't been released yet (Expected: 2020-03-15 00:00:00)
> 2020-03-14 09:13:10 VERBOSE  discover      discover-shows  Searching for `The Blacklist S04E22` with plugin `search_rss` (1 of 11)
> 2020-03-14 09:13:10 VERBOSE  discover      discover-shows  Searching for `Victoria S03E08` with plugin `search_rss` (2 of 11)
> 2020-03-14 09:13:10 VERBOSE  discover      discover-shows  Searching for `Poldark S05E07` with plugin `search_rss` (3 of 11)
> 2020-03-14 09:13:11 VERBOSE  discover      discover-shows  Searching for `Poldark S05E08` with plugin `search_rss` (4 of 11)
> 2020-03-14 09:13:11 VERBOSE  discover      discover-shows  Searching for `Brooklyn Nine-Nine S07E07` with plugin `search_rss` (5 of 11)
> 2020-03-14 09:13:11 VERBOSE  discover      discover-shows  Searching for `Grey's Anatomy S16E17` with plugin `search_rss` (6 of 11)
> 2020-03-14 09:13:11 VERBOSE  discover      discover-shows  Searching for `Better Call Saul S05E02` with plugin `search_rss` (7 of 11)
> 2020-03-14 09:13:12 VERBOSE  discover      discover-shows  Searching for `Better Call Saul S05E03` with plugin `search_rss` (8 of 11)
> 2020-03-14 09:13:12 VERBOSE  discover      discover-shows  Searching for `Better Call Saul S05E04` with plugin `search_rss` (9 of 11)
> 2020-03-14 09:13:12 VERBOSE  discover      discover-shows  Searching for `The Marvelous Mrs. Maisel S03E08` with plugin `search_rss` (10 of 11)
> 2020-03-14 09:13:12 VERBOSE  discover      discover-shows  Searching for `Star Trek: Picard S01E08` with plugin `search_rss` (11 of 11)

With your config:

> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Downton Abbey S06E02 Episode 2` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `The Blacklist S04E06 The Thrushes` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Modern Family S08E09 Snow Ball` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `The Vampire Diaries S08E06 Detoured On Some Random Backwoods Path to Hell` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Sherlock S04E01 The Six Thatchers` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Blindspot S02E10 Nor I, Nigel, AKA Leg in Iron` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Family Guy S15E10 Passenger Fatty-Seven` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Marvel's Agents of S.H.I.E.L.D. S04E09 Broken Promises` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `New Girl S06E07 Last Thanksgiving` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Brooklyn Nine-Nine S04E13 The Audit` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `The Last Man on Earth S03E10 Got Milk?` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `The Big Bang Theory S10E13 The Romance Recalibration` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Grey's Anatomy S13E10 You Can Look (But You'd Better Not Touch)` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `The Walking Dead S07E09 Rock in the Road` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Supernatural S12E09 First Blood` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Better Call Saul S03E01 Mabel` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `iZombie S03E01 Heaven Just Got a Little Bit Smoother` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Vikings S05E01 The Fisher King` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Dark S02E01 Beginnings and Endings` by accept_all plugin
> 2020-03-14 09:11:00 VERBOSE  task          fill-series-episode-list ACCEPTED: `Veronica Mars S04E01 Spring Break Forever` by accept_all plugin

I think they are all watched episodes. Some of them the first episode from the last season some them don't.

**Pull request closed without merging**
