### PR TITLE
[Change] Accept Input Plugins in `content_filter`

### PR DESCRIPTION
**Pull request by BrutuZ**
### Motivation for changes:
Wanted to reuse a list for `crossmatch` in `content_filter`

### Detailed changes:
- Added list plugins to schema under the `from` key to keep consistency with other plugins

### Addressed issues/feature requests:
- Fixes my use-case :P

### Config usage if relevant (new plugin or updated schema):
```yaml
      content_filter:
        [regexp_mode: yes]
        require:
          - '*.avi'
          - '*.mkv'
        reject:
          from:
            - regexp_list: my-rejections
            - mock: ['forbidden_file.ext']
```
### Log and/or tests output (preferably both):
```
$ pytest -v test_content_filter.py
=========================================================================================================== test session starts =========================================================================================================== platform win32 -- Python 3.11.4, pytest-7.4.4, pluggy-1.5.0 -- Flexget\Scripts\python.exe
cachedir: .pytest_cache
rootdir: Flexget
configfile: pyproject.toml
plugins: anyio-4.4.0, base-url-2.1.0, cov-6.0.0, playwright-0.4.4, xdist-3.6.1, time-machine-2.13.0
collected 17 items

test_content_filter.py::TestContentFilter::test_reject1 PASSED                                                                                                                                                                       [  5%] test_content_filter.py::TestContentFilter::test_reject2 PASSED                                                                                                                                                                       [ 11%] test_content_filter.py::TestContentFilter::test_require1 PASSED                                                                                                                                                                      [ 17%] test_content_filter.py::TestContentFilter::test_require2 PASSED                                                                                                                                                                      [ 23%] test_content_filter.py::TestContentFilter::test_require_all1 PASSED                                                                                                                                                                  [ 29%] test_content_filter.py::TestContentFilter::test_require_all2 PASSED                                                                                                                                                                  [ 35%] test_content_filter.py::TestContentFilter::test_strict PASSED                                                                                                                                                                        [ 41%] test_content_filter.py::TestContentFilter::test_cache PASSED                                                                                                                                                                         [ 47%] test_content_filter.py::TestContentFilter::test_min_files PASSED                                                                                                                                                                     [ 52%] test_content_filter.py::TestContentFilter::test_max_files PASSED                                                                                                                                                                     [ 58%] test_content_filter.py::TestContentFilter::test_list_require_a PASSED                                                                                                                                                                [ 64%] test_content_filter.py::TestContentFilter::test_list_require_r PASSED                                                                                                                                                                [ 70%] test_content_filter.py::TestContentFilter::test_input_require_a PASSED                                                                                                                                                               [ 76%] test_content_filter.py::TestContentFilter::test_input_require_r PASSED                                                                                                                                                               [ 82%] test_content_filter.py::TestContentFilter::test_input_require_all PASSED                                                                                                                                                             [ 88%] test_content_filter.py::TestContentFilter::test_regexp_require_a PASSED                                                                                                                                                              [ 94%] test_content_filter.py::TestContentFilter::test_regexp_require_r PASSED                                                                                                                                                              [100%]

============================================================================================================ warnings summary ============================================================================================================= ..\..\Lib\site-packages\flask_restx\api.py:19
..\..\Lib\site-packages\flask_restx\api.py:19
  Flexget\Lib\site-packages\flask_restx\api.py:19: DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
    from jsonschema import RefResolver

flexget/tests/test_content_filter.py::TestContentFilter::test_reject1
  Flexget\Lib\site-packages\babelfish\converters\__init__.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import iter_entry_points, EntryPoint

flexget/tests/test_content_filter.py::TestContentFilter::test_reject1
  Flexget\Lib\site-packages\pkg_resources\__init__.py:3149: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

flexget/tests/test_content_filter.py::TestContentFilter::test_reject1
  Flexget\Lib\site-packages\pkg_resources\__init__.py:3149: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

flexget/tests/test_content_filter.py::TestContentFilter::test_reject1
  Flexget\Lib\site-packages\telegram\files\inputfile.py:22: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
    import imghdr

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================================================== 17 passed, 6 warnings in 9.73s ======================================================================================================
```

### To do:
- Update [documentation](https://flexget.com/Plugins/content_filter)
<details><summary>Updated docs page</summary>

````markdown
# Content Filter
This allows filtering based on the filenames inside of torrents.
> This plugin does not accept entries on its own, only rejects already accepted entries that do not pass your requirements. You'll need another [filter plugin](/Plugins#Filters) in the task to accept the entries you want.
{.is-info}

> `content_filter` doesn't work with magnet links, as it works by analyzing the file list present in the .torrent file. You can include the [magnets](/Plugins/magnets) plugin to reject any magnet entries.
{.is-warning} 
 
 |---|---|---|
 | Field | Default | Description |
 | `require` | `None` | Reject the entry if **none** of the files in the torrent matches **any** of the masks |
 | `reject` | `None` | Reject the entry if **any** of the files in the torrent matches **any** of the masks |
 | `require_all` | `None` | Reject the entry if **all** of the masks **do not** match across the files in the torrent |
 | `reject_all` | `None` | Reject the entry if **all** of the masks match across the files in the torrent |
 | `require_mainfile` | `false` | Reject the entry unless the torrent contains a single file or one of the files accounts for at least 90% of the size |
 | `strict` | `false` | Reject the entry if `content_filter` is unable to parse its files |
 | `regexp_mode` | `false` | Switches filename matching from filesystem patterns to case-insensitive Regular Expressions |

For the requirement and rejection fields, you can specify a single mask, a list of masks or an input plugin.



## Examples
- Reject torrents that do not have mkv file in them:
```
content_filter:
  require: '*.mkv'
```
- Reject torrents that have rars in them:

```
content_filter:
  reject: '*.rar'
```
- Reject torrent if it doesn't have mp4 OR mkv in it. Reject also if there are wmv files
```
content_filter:
  require:
    - '*.mp4'
    - '*.mkv'
  reject: '*.wmv'
```
- Reject torrents that don't have a matroska container AND a nfo file:
```
content_filter:
  require_all: 
    - '*.mkv'
    - '*.nfo'
```
- Reject multifile torrents that don't have one file at least 90% of total size (single-file torrents are not affected)
```
content_filter:
  require_mainfile: yes
```
- Reject torrent if none of its files match any of the entries in a previously populated [`regexp_list`](/Plugins/List/regexp_list)
```
content_filter:
  regexp_mode: yes
  require:
    from:
      - regexp_list: my-wanted-files
```
````

### CODE REVIEW

**Comment by gazpachoking** [comment]
Interesting. This is sorta like how configure_series works then? Would this be better to use the input plugin interface rather than list plugin interface? I believe all the list plugins implement both. I like this idea, I wonder if there is a clean way to make it more generic. Seems like there could be a few areas where we would like to do similar things.

**Comment by BrutuZ** [comment]
More like `crossmatch` since it was part of the template for some of the changes, but sure, _kinda_ like `configure_series` for the `from` key usage like mentioned in the opening.
I suppose going for inputs instead of just lists does make more sense. I just went for lists at first because that's what I'm using 😅

Took the chance while at it and added an optional `regexp_mode` boolean key so the user can choose to match using Regular Expressions (implied partial matching, case-insensitive) instead of `fnmatch` (explicit partial matching via glob-like pattern, system-based case-sensitivity)

**Comment by BrutuZ** [comment]
Should be good to go now @gazpachoking 
I just hope the changes on today's version bump didn't cause anything to break on this

**Comment by gazpachoking** [comment]
Looks good to me. I still feel like it would be nice to come up with a more generic or reusable way to do this in more plugins, but don't want to hold this up right now.

**Pull request merged**
