### PR TITLE
Version checker plugin

### PR DESCRIPTION
**Pull request by liiight**
A builtin plugin that checks whether user is running the latest flexget version and place a log warning if not.

*    Checks via interval to avoid hammering, default is 1 day.
*    Can accept bool or [`always`, `by_interval`] in config.
*    Can also accept object. If `check_for_dev_version` option is True, version will be checked even if current release is dev, otherwise, it will be skipped.

### CODE REVIEW

**Comment by lepinkainen** [comment]
Could this plugin output a message on a standard output plugin somehow? It'd need to be throttled of course, I don't want a version notification every 5 minutes =)

**Comment by liiight** [comment]
it runs only once a day by default and can be set to any value via config

**Comment by alneven** [comment]
is this working for you guys?

```
# ~/flexget-dev/bin/flexget -V
1.2.427.dev
# ~/flexget-dev/bin/flexget daemon reload
There is a FlexGet process already running for this config, sending execution there.
2016-01-11 19:53 INFO     manager                       Reloading config from disk.
2016-01-11 19:53 CRITICAL manager                       [/tasks/check_version] The key `version_checker` is not valid here. Only known plugin names are valid keys.
2016-01-11 19:53 ERROR    manager                       Error loading config: Did not pass schema validation.
```

If I add it as:
```
tasks:
    check_version:
        template:
          - email_notification
        version_checker:
          lookup: by_interval
          check_for_dev_version: yes
          interval: 1
```
It fails to reload the config.

If I add it very simple, as in the wiki
```
tasks:
  check_version:
    version_checker: yes
```
It fails as well...


If I execute the task directly with *--debug* and *--test*:

```
2016-01-11 19:49 DEBUG    plugin                        Trying to load plugins from: [u'/root/.flexget/plugins', '/root/flexget-dev/flexget/plugins']
...
2016-01-11 19:49 DEBUG    schema                        Initializing plugin version_checker schema version to 0
2016-01-11 19:49 DEBUG    manager                       config_name: config
2016-01-11 19:49 DEBUG    manager                       config_base: /root/.flexget
2016-01-11 19:49 DEBUG    manager                       New config data loaded.
2016-01-11 19:49 DEBUG    cron_env                      Encoding UTF-8 stored
2016-01-11 19:49 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2016-01-11 19:49 DEBUG    task_queue                    task queue shutdown requested
2016-01-11 19:49 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-01-11 19:49 INFO     ipc.rpyc                      server started on [127.0.0.1]:52136
2016-01-11 19:49 DEBUG    task          check_version   executing check_version
2016-01-11 19:49 DEBUG    template      check_version   Merging template email_notification into task check_version
2016-01-11 19:49 DEBUG    template      check_version   Merging template global into task check_version
2016-01-11 19:49 WARNING  version_checker check_version   You are not running latest Flexget Version. Current is 1.2.427.dev and latest is 1.2.426
2016-01-11 19:49 DEBUG    version_checker check_version   creating instance of last version check in DB
2016-01-11 19:49 WARNING  task          check_version   Task doesn't have any input plugins, you should add (at least) one!
2016-01-11 19:49 DEBUG    backlog       check_version   0 entries purged from backlog
```



I have updated earlier the local flexget environment, as usually:
```
# cd ~/flexget-dev && git pull
remote: Counting objects: 91, done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 91 (delta 57), reused 29 (delta 29), pack-reused 12
Unpacking objects: 100% (91/91), done.
From https://github.com/Flexget/Flexget
   a655f31..500cd2b  develop    -> origin/develop
   a21cb50..ded86c3  master     -> origin/master
 * [new tag]         1.2.426    -> 1.2.426
Updating a655f31..500cd2b
Fast-forward
 flexget/_version.py                                          |    2 +-
 flexget/manager.py                                           |   26 +++++++-------
 flexget/plugins/operate/version_checker.py                   |  115 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 flexget/plugins/plugin_transmission.py                       |    6 ++--
 flexget/utils/imdb.py                                        |   22 +++++++-----
 flexget/utils/tools.py                                       |   49 ++++++++++++++++++++-------
 tests/cassettes/test_imdb_parser.TestImdbParser.test_no_year |  310 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/test_imdb_parser.py                                    |    9 +++++
 8 files changed, 501 insertions(+), 38 deletions(-)
 create mode 100644 flexget/plugins/operate/version_checker.py
 create mode 100644 tests/cassettes/test_imdb_parser.TestImdbParser.test_no_year
```

**Comment by liiight** [comment]
You need to stop and restart daemon after upgrade. Reload doesn't load new files.

**Comment by alneven** [comment]
ooo, shit, totally forgot... :-(

On Mon, Jan 11, 2016 at 8:32 PM, Or Carmi <notifications@github.com> wrote:

> You need to stop and restart daemon after upgrade. Reload doesn't load new
> files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flexget/Flexget/pull/744#issuecomment-170664414>.
>



-- 
http://www.keksz.net
news & photoportal

**Comment by liiight** [comment]
Ironically this was one of the motivations for this plugin :smile:

For future reference, if the task worked manually and not via daemon, that's a dead give away. 

No worries though, thanks for reporting

**Comment by alneven** [comment]
with the today's pull the version_checker in config gives problems:

```
# git pull
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/Flexget/Flexget
   3b8114b..97d8da3  develop    -> origin/develop
   b268a1a..39331ca  master     -> origin/master
 * [new tag]         1.2.434    -> 1.2.434
Updating 3b8114b..97d8da3
Fast-forward
 flexget/_version.py |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
```
2016-01-22 18:30 CRITICAL manager                       [/tasks/check_version] The key `version_checker` is not valid here. Only known plugin names are valid keys.
2016-01-22 18:30 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
```


I have removed the part from the config, as I'm on -dev, so therefore it's not needed.
And now I have no problems at all.

Just wanted to make sure I report it. ;-)

**Comment by liiight** [comment]
working for me:
```
2016-01-24 10:58 WARNING  version_checker task1           You are not running latest Flexget Version. Current is 1.2.437.dev and latest is 1.2.436
```
Also, for any issues please use the forum, I think it's more convinient.

**Pull request merged**
