### PR TITLE
adding missing 4k categories for filelist.py

### PR DESCRIPTION
**Pull request by rareshornet**
### Motivation for changes:
Missing flielist.py site 4k categories
### Detailed changes:
- movies 4k, movies 4k blueray and series 4k

### Addressed issues:
- Fixes # .

### Implemented feature requests:
- Feathub #[XX](https://feathub.com/Flexget/Flexget/+XX).

### Config usage if relevant (new plugin or updated schema):
```
paste_config_here
```
### Log and/or tests output (preferably both):
```
paste output here
```
#### To Do:

- [ ] Stuff..
This is quite a small change, no function to the python code was changed, I added categories based on what filelist reports the index numbers are for each new category.

### CODE REVIEW

**Comment by gazpachoking** [comment]
Can you open this pull request against the develop branch? We don't merge directly into master.

**Comment by liiight** [comment]
No need to reopen, you can edit the PR and change the base branch

**Comment by rareshornet** [comment]
done!

**Comment by gazpachoking** [comment]
Thanks!

**Pull request merged**
