### PR TITLE
Added 'serialize' method.

### PR DESCRIPTION
**Pull request by metaMMA**
### Motivation for changes: 
Serialization was needed to output the the entry list as a `JSON` file.

### Detailed changes: 
- Added a method to the `Entry` class called `serialize`. `entry.serialize()` returns a python dictionary that is ready to be used in file outputs like `json.dump`, or for use in writing `text`, `csv`, `html`, etc. files.  It was added here, so that anywhere an entry exists, it can always be serialized easily.

#### To Do:

- [ ] Discuss if this is wanted/needed
- [ ] Discuss best location for this method

### CODE REVIEW

**Comment by liiight** [comment]
I'm not sure this is needed. You can already call `dict(entry)` to get a dict, and I think the custom serialization of non trivial fields should go in our json util (which they already do).

**Comment by metaMMA** [comment]
I think the only issue might be with the `Quality` object. If I use the `datetime_encoding=True` flag, I'm not sure it will convert the `Quality` object to a string.

**Comment by liiight** [comment]
Perhaps that will need an additional encoder then

**Comment by paranoidi** [comment]
In order this to be useful it should be able to serialize & deserialize lazy fields and other object based fields like quality.

**Comment by metaMMA** [comment]
> In order this to be useful it should be able to serialize & deserialize lazy fields and other object based fields like quality.

Agreed. I'm hoping to start work on the `de-serialization` method this week.

**Comment by paranoidi** [comment]
Superseded by #2517

**Pull request closed without merging**
