### PR TITLE
fix: transmission-rpc deprecated base64 torrent content

### PR DESCRIPTION
**Pull request by trim21**
### Detailed changes:
- no need to encode torrent content to base64, removed in new transmission-rpc version

### Addressed issues/feature requests:
- Fixes # .

### CODE REVIEW

**Comment by gazpachoking** [comment]
👍 Thanks!

**Comment by ksurl** [comment]
What version of transmission-rpc is required for this? Latest 4.1.3?

**Comment by trim21** [comment]
> What version of transmission-rpc is required for this? Latest 4.1.3?

no requirement

**Comment by foreign-sub** [comment]
spitsout : TypeError: Object of type bytes is not JSON serializable (line 422)
ok when reverted

Python 3.9.2, flexget 3.5.31, transmission-rpc 3.2.5

**Comment by trim21** [comment]
> spitsout : TypeError: Object of type bytes is not JSON serializable (line 422) ok when reverted
> 
> Python 3.9.2, flexget 3.5.31, transmission-rpc 3.2.5

try upgrade to newer transmission-rpc version

**Comment by foreign-sub** [comment]
thanks i will give it a try, but this means there is some requirement at least

**Comment by ksurl** [comment]
Please open a separate issue. This pr is merged. Your version was already behind a couple minor versions (latest on v3 is 3.4.2)

**Pull request merged**
