### PR TITLE
Extend movie-list Plugin to support DUBBED Movies

### PR DESCRIPTION
**Pull request by Lorenz1508**
Extend existing Plugin to support DUBBED Movies from imdb_id, trakt_movie_id and tmdb_id

modify flexget/plugins/list/ and add the ability to handle dubbed movies.

add ISO 3166 that defines codes for the names of countries

Extended from the existing example on the wiki:

flexget movie-list add tmdb_id=127380 will add finding dory 

and add the dubbed movies lets say PL, RU, DE, FR, JP, IT so Maybe adding a new syntax like this

flexget movie-list add tmdb_id=127380 PL will add The Polish synchronized version Gdzie jest Dory
flexget movie-list add tmdb_id=127380 RU will add The Russian synchronized version В поисках Дори 
flexget movie-list add tmdb_id=127380 DE will add The German synchronized version Findet Dorie
flexget movie-list add tmdb_id=127380 FR will add The French synchronized version Le Monde de Dory
flexget movie-list add tmdb_id=127380 JP will add The Japanese synchronized version ファインディング・ドリー
flexget movie-list add tmdb_id=127380 IT will add The Italian synchronized version Alla ricerca di Dory

And so on .....

### CODE REVIEW

**Comment by liiight** [comment]
You didn't open this pr correctly. Fork the repo and submit a pr from your clone to the main one, on develop branch

**Comment by Lorenz1508** [comment]
like this ?

https://github.com/Lorenz1508/Flexget

I really only want to make a Request fo new function

**Comment by liiight** [comment]
wait, you wanted to request a feature or wanted to submit a pull request?

**Comment by Lorenz1508** [comment]
well i want to request a feature But does not know how and where

**Comment by liiight** [comment]
yeah, that's not what a pull request is.
Just open an issue [here](https://github.com/Flexget/Flexget/issues/new)

**Comment by Lorenz1508** [comment]
Done 
thanks

**Pull request closed without merging**
