### PR TITLE
Strips Special Charters from KAT

### PR DESCRIPTION
**Pull request by soloam**
Removes special charters from KAT search

### CODE REVIEW

**Comment by soloam** [comment]
Sorry #492 and #493 where supposed to be in the same patch, but they ended up separated, one is depended of the other.

**Comment by soloam** [comment]
Hello, is this closed? Never had a feedback on if this will be usefull for flexget.

Thank You

**Comment by liiight** [comment]
@soloam is this still relevant?

**Comment by soloam** [comment]
@liiight hello, yes, this would add the clean_title to kat search! The one #492.

**Pull request merged**
