### PR TITLE
Cross build docker images for more arch

### PR DESCRIPTION
**Pull request by maxcanna**
### Detailed changes:
- 

### Addressed issues/feature requests:
- Fixes # .

### Config usage if relevant (new plugin or updated schema):
```
paste_config_here
```
### Log and/or tests output (preferably both):
```
paste output here
```
#### To Do:

- [ ] Stuff..

### CODE REVIEW

**Comment by trim21** [comment]
it failed in these lines:


https://github.com/Flexget/Flexget/blob/bf0fd6d311f66fd89f7490a3682f1ce8de43a48f/Dockerfile#L17-L18

You will need a cross arch way to bundle-webui

**Comment by maxcanna** [comment]
@trim21 It's working now. Perhaps I'm too naive here but wouldn't something like this:

https://github.com/maxcanna/dockerfiles/blob/master/flexget/Dockerfile

suffice?

**Comment by maxcanna** [comment]
@trim21 any updates on this? I saw #3748 but perhaps we can go with this in the meantime. Wdyt?

**Comment by trim21** [comment]
I don't have write permission, you need to ask @gazpachoking

**Comment by gazpachoking** [comment]
Seems good to me. We could probably split our `dev` requirements group into `dev` and `release` (to eliminate the ruff install, and the need for cargo here) but that could come in a separate PR. LGTM, thanks!

**Comment by gazpachoking** [comment]
@maxcanna Which platforms were you actually needing? I pulled some out that were harder to support due to lack of prebuilt wheels on pypi. Left arm64 in there other than the default amd64.

**Comment by maxcanna** [comment]
@gazpachoking I need `linux/arm/v7` in order to be able to run it on raspberry PI on 32 bit OS. Thank you for taking this into account

**Pull request merged**
