### PR TITLE
[change] next_series_episode: Opt to act based on downloaded status

### PR DESCRIPTION
**Pull request by kepi**
### Motivation for changes:

There are cases where it is beneficial to have some plugin which emits all episodes of series or downloaded only. And `next_series_episode` does already almost everything needed.

For me, the main use case is to be able to forget downloads for episodes which were in fact not downloaded. I.e. passed to pyload but pyload failed to download them in the end.

But while working on this I realized that there are more use cases to this so I added also `only` value which might get handy.

I'm not sure if option name is ok and clear. Let me know if there is anything I can do to improve.

### Detailed changes:

New option `downloaded` for plugin `next_series_episode` were value is one of:

- no: (default) Same behavior as before. Don't include already downloaded episodes.
- yes: Include all episodes no matter the downloaded state.
- only: Include only already downloaded episodes.

### Config usage if relevant (new plugin or updated schema):

```
    next_series_episodes:
      backfill: yes
      from_start: yes
      downloaded: only
```

### CODE REVIEW

**Comment by kepi** [comment]
Is there any chance to have this merged? Can I help somehow?

**Comment by kepi** [comment]
bump

**Comment by perriernical** [comment]
any updates?

**Comment by gazpachoking** [comment]
I was pretty confused about the actual behavior here before. So when 'downloaded' is True, it emits every episode from the current season? When False it's the previous behavior of only undownloaded eps from this season, when 'only' it's all downloaded eps from current season? How does it interact with backfill?

**Comment by paranoidi** [comment]
Very confusing option, "downloaded: yes | no | only"

aren't yes and only same thing?

**Pull request closed without merging**
