### PR TITLE
Handle not existing or invalid secrets file

### PR DESCRIPTION
**Pull request by antivirtel**
Fix this unhandled exception: http://paste2.org/KAKAN6Kf

### CODE REVIEW

**Comment by stevezau** [comment]
@gazpachoking what do you mean by 'config validation'? I thought the config validation just validates against the json schema?? Which would mean @antivirtel changes are valid?

**Comment by antivirtel** [comment]
No, they are not, it's still WIP!

**Comment by stevezau** [comment]
@antivirtel this PR is still WIP?? It's been over 8month so i assumed it was forgotten .. heh

**Comment by antivirtel** [comment]
Sorry, I'd no time to work on this. I'll have in this month finally!

**Comment by stevezau** [comment]
@antivirtel no problems... I changed the title to [WIP]

**Comment by antivirtel** [comment]
File does not exist:
```
$ flexget check
2015-07-11 16:00 INFO     check                         Checking config file `~/.flexget/config.yml`
2015-07-11 16:00 WARNING  check                         Config line 4 is likely missing ':' at the end
2015-07-11 16:00 WARNING  check                         Config line 7 is likely missing ':' at the end
2015-07-11 16:00 WARNING  check                         Config line 10 is likely missing ':' at the end
2015-07-11 16:00 CRITICAL secrets                       Secrets' config file '/home/roland/.flexget/secrets.yml' does not exist or you have no read permission!
Could not initialize manager: ~/.flexget/secrets.yml
```
Invalid secrets config file:
```
$ flexget check
2015-07-11 14:59 INFO     check                         Checking config file `~/.flexget/config.yml`
2015-07-11 14:59 WARNING  check                         Config line 4 is likely missing ':' at the end
2015-07-11 14:59 WARNING  check                         Config line 7 is likely missing ':' at the end
2015-07-11 14:59 WARNING  check                         Config line 10 is likely missing ':' at the end
2015-07-11 14:59 CRITICAL secrets                       Invalid secrets file: '/home/roland/.flexget/secrets.yml'.
2015-07-11 14:59 CRITICAL manager                       Failed to load config file: Invalid secrets file: '~/.flexget/secrets.yml'.
Could not initialize manager: Invalid secrets file: '~/.flexget/secrets.yml'.
```

**Comment by gazpachoking** [comment]
@antivirtel Sorry I didn't see this when you updated. Can you update and make sure it still works?

**Comment by liiight** [comment]
Is this relevant?

**Comment by antivirtel** [comment]
@gazpachoking I'll try to test it this weekend, I hope I'll have time.

@liiight how you mean that?

**Comment by liiight** [comment]
I'm just going over all prs, pinging the openers. If you're on it it's great

**Comment by liiight** [comment]
Reopen if relevant

**Pull request closed without merging**
