### PR TITLE
[WIP] Enhance anidb_list

### PR DESCRIPTION
**Pull request by XVicarious**
### Motivation for changes:
AniDB has a ton of filters you can use to filter your wishlist (and other lists for that matter). So I have taken the time to document all of those, and start to implement them.

Another change that I have not made, but would like to after discussion is renaming this plugin from `anidb_list` to `anidb_wishlist` because what what we are dealing with here is the wishlist and not the "list" (or "mylist").

#### Documentation of Options:
Adult Content: (only works when you're logged in) (choose 1)
h=0 (default) "Ignore"
h=1 "Hide Adult Content"
h=2 "Show Only Adult Content"

Airing: (choose 1)
airing=0 (default) "Ignore"
airing=1 "Still Airing"
airing=2 "Finished"
airing=3 "Finished/Unknown"

Types: (all =1)
type.tvspecial "TV Specials"
type.tvseries "TV Series"
type.ova "OVA"
type.movie "Movie"
type.web "Web"
type.unknown "Unknown"
type.musicvideo "Music Video"

Misc: (all =1)
streamable "Streamable" (legally streamable)
\# The following require you to be logged in
lang.sub.pref (Use Subtitle Langauge Pref, meaning has subtitles in the language that you perfer)
lang.dub.pref (Use Audio Language Pref, meaning the audio is in the langauge you perfer)

Buddy: (only works when you're logged in) (choose 1)
buddy=0 (default) "Ignore"
buddy=1 "Show if in mylist" (shows items in your buddys lists that are also in your list)
buddy=2 "Hide if in mylist" (opposite of above)
buddy=3 "Show if watched" (show items in your buddys lists if you watched them)
buddy=4 "Hide if watched" (opposite of above)

Mylist State: (only works if you're logged in*)
liststate.watching=1
liststate.unknown=1
liststate.collecting=1
liststate.completed=1
liststate.stalled=1
liststate.dropped=1

Mylist Status: (only works if you're logged in*)
mylist=0 (default) "Ignore"
mylist=1 "Complete"
mylist=2 "Incomplete"
mylist=3 "in mylist" (this is set if you use anything in the "Mylist State", or "Watched Status" categories)
mylist=4 "not in mylist"
mylist=5 "related & not in mylist"

Notifications: (choose 1)
notification=0 (default) "Ignore"
notification=1 "Enabled"
notification=2 "Disabled"

Vote Status (choose 1)
vote=0 (default) "Ignore"
vote=1 "Permanent"
vote=2 "Temporary"
vote=3 "None"
vote=4 "Either"

Watched Status (only works if you're logged in*) (all =1)
watched.unwatched
watched.partial
watched.complete
watched.allihave

* This may be dependent on your mylist privacy settings

### Detailed changes:
- Changed Following Options:
  - `type` 
    - Now includes all types of media AniDB has, and is filtered through URL parameters instead of being detected on parsing the HTML.
    - It now has no default and is ignored if it is not set.
    - It can be one (or zero) or more items
  - `mode` now technically doesn't have a "default", it is just simply ignored if it is not there
- Added Options:
  - `is_airing`, optional, can be `airing`, `finished`, `unknown`, or if you want to be verbose `ignore`
  - `adult_only`, optional, can be `hide`, `only`, or if you want to be verbose `ignore`
    - This setting only matters if you use `form` to log in as NSFW content is hidden to non-registered users
    - **OPINIONS PLEASE**: There are three states that this can be in. Ignored, Only, and None. I feel this can be a boolean, but I have no idea what the parameter should be called. My personal opinion (as it is the default behavior of AniDB itself) is that default should be `ignore`. Although as I write this, `hide` and `only` are not bad options and almost as good as boolean
  - `buddy_lists`, optional, can be `show_in`, `hide_in`, `show_watched`, `hide_watched`, or if you want to be verbose `ignore`
    - You need to be logged in for this setting to work with `form`
  - `mylist`, optional, can be `complete`, `incomplete`, `in_mylist`, `not_in_mylist`, `related_not_in_mylist`, blah blah blah `ignore`
    - **OPINIONS PLEASE**: `in_mylist` is fine, `not_in_mylist` is toeing the line, and `related_not_in_mylist` is (imo) over the naming line
    - `mylist` has two suboptions
      - `status`, optional, is whatever `mylist` can be set to
      - `state`, optional, can be `watching`, `unknown`, `collecting`, `stalled`, and `dropped`
  - `watched`, optional, can be `unwatched`, `partial`, `complete`, or `allihave`
  - `voted`, optional, be 'permanent`, `temporary`, `none`, `either`, blah blah blah `ignore`

### Config usage if relevant (new plugin or updated schema):
```
        anidb_list:
          user_id: <required>
          type: # zero or more
            - tvseries
            - tvspecial
            - ova
            - movie
            - web
            - musicvideo
          is_airing: (ignore)/airing/finished/unknown
          adult_only: boolean  # if adult_only is not present, it will be ignored
          buddy_lists: (ignore)/show_in/hide_in/show_watched/hide_watched
          mylist: # this option can also just be the value of "status"
            status: (ignore)/complete/incomplete/in_mylist/not_in_mylist/related_not_in_mylist
            state: watching/unknown/collecting/stalled/dropped
          watched: # zero or more
            - unwatched
            - partial
            - complete
            - allihave
          mode: (all)/undefined/watch/get/blacklist/buddy
          pass: <guest pass set on anidb settings>
          voted: (ignore)/permanent/temporary/none/either
          strip_dates: (no)/yes
```
### Log and/or tests output (preferably both):
```
```
#### To Do:
- [ ] Properly parse the type
- [ ] Add `voted` to schema
- [ ] Add `notifications` to schema?

### CODE REVIEW

**Comment by vxcamiloxv** [comment]
this would be useful, is still on progress? @XVicarious  do you need help?

**Comment by XVicarious** [comment]
Its almost done. I just have to fix some of the options and clean up building the parameters. I'll try to get this done by Friday. I'm also conflicted if I should add mylist support (which I have on my own machine), however AniDB looks down upon web scraping and their admin is fairly temperamental  and unforgiving. I might end up implementing mylist as a list plugin. The wishlist should be safe because it doesn't have any API access (its only been 15 years...), and I'm pretty sure they allow that due to the circumstances.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by XVicarious** [comment]
God, I'm a mess. Either way, I'm sorry about the hold up with this. It was more or less done Friday, but I hadn't rebased on develop yet. That is done. I forgot to squash it. But it gets squashed when you merge anyway. Let me know if you do want me to fix that and I'll try.

**Comment by gazpachoking** [comment]
Hmm, it seems something got a bit messed up with the merge, this PR is claiming 554 files got changed (maybe you rebased develop on top of your branch rather than the other way around?) ;) Can you try to clean that up so that we can see a proper diff before merging it back in?

**Comment by paranoidi** [comment]
@XVicarious sorry, closing due inactivity. Hoping to see new clean PR!

**Pull request closed without merging**
