### PR TITLE
[add] quality: add color range

### LINKED ISSUE #2835: Color range(HDR) as a quality component?
Hi, now that HDR is becoming more and more common, is it time to create a new component called something like color range? With the following options ordered in best to worse:

- Dolby Vision
- HDR10+
- HDR10
- 10bit (move existing 10bit from codecs where it does not belong)
- 8bit (assumed default)

Some relevant links: [Wikipedia](https://en.wikipedia.org/wiki/High-dynamic-range_video) and [scenerules for x265](https://scenerules.org/t.html?id=2020_X265.nfo) and [scenerules for web rips](https://scenerules.org/t.html?id=2020_WDX.nfo)

### PR DESCRIPTION
**Pull request by soloam**
### Motivation for changes:
Hi, now that HDR is becoming more and more common, is it time to create a new component called color range

### Detailed changes:
- quality.py - Add support to color range

**BREAKING CHANGES:** Removed 10bit from codecs

### Addressed issues:
- Fixes #2835

### Config usage if relevant (new plugin or updated schema):
```
tasks:
  quality_test:
    disable:
      - remember_rejected
      - seen
      - retry_failed
      - seen_info_hash
    quality: hdrplus+
```
### Log and/or tests output (preferably both):

```
flexget execute --inject "My Movie UHD 2160P HDR+ DTS-HD" --dump

2021-04-29 01:07:30 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-04-29 01:07:30 VERBOSE  details       quality_test    Summary - Accepted: 0 (Rejected: 0 Undecided: 1 Failed: 0)
2021-04-29 01:07:30 WARNING  task          quality_test    Task doesn't have any output plugins, you should add (at least) one!
-- Undecided: --------------------------
title            : My Movie UHD 2160P HDR+ DTS-HD
url              : http://localhost/inject/dB1LsEkNcTJjuOvwPgziHeQCyXIhMZ
original_url     : http://localhost/inject/dB1LsEkNcTJjuOvwPgziHeQCyXIhMZ
media_id         : <LazyField - value will be determined when it is accessed>
original_title   : My Movie UHD 2160P HDR+ DTS-HD
quality          : 2160p hdrplus dtshd
task             : quality_test
```
```
flexget execute --inject "My Movie UHD 2160P HDR DTS-HD" --dump

2021-04-29 01:08:13 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-04-29 01:08:13 VERBOSE  task          quality_test    REJECTED: `My Movie UHD 2160P HDR DTS-HD` by quality plugin because `2160p hdr10 dtshd` does not match any of quality requirements: `hdrplus+`
2021-04-29 01:08:13 VERBOSE  details       quality_test    Summary - Accepted: 0 (Rejected: 1 Undecided: 0 Failed: 0)
2021-04-29 01:08:13 WARNING  task          quality_test    Task doesn't have any output plugins, you should add (at least) one!
-- Rejected: ---------------------------
title            : My Movie UHD 2160P HDR DTS-HD
url              : http://localhost/inject/Oc1KUiNMnlstgjHRk3ADZIfdx6p0BY
original_url     : http://localhost/inject/Oc1KUiNMnlstgjHRk3ADZIfdx6p0BY
media_id         : <LazyField - value will be determined when it is accessed>
original_title   : My Movie UHD 2160P HDR DTS-HD
quality          : 2160p hdr dtshd
task             : quality_test

```

#### To Do:
I tested the regex against several entries from trackers and seems ok, but:
- [ ] Fine Tune Regex

### CODE REVIEW

**Comment by BrutuZ** [comment]
Dropping my two cents out here, feel free to pick them up or leave them on the ground xD

- I'm kind of missing a more intuitive `hdr` item. Any reason not to call `hdr10` just `hdr` and give it a lower ranking than `hdrp` (`hdrplus` is probably clearer too)?
- The `p` on Hi10/8p should be optional, I have seen just `Hi10` floating around.

`[feat!]` won't be auto-added to the Changelog 😝
https://github.com/Flexget/Flexget/blob/5bf24e774af4582d74658df742bc8a1f2ede43b5/update-changelog.py#L12-L18

**Comment by denngie** [comment]
Great work @soloam! Quick question, the [doc page for quality](https://flexget.com/Plugins/quality) lists hdr above hdrplus, that can't be intended right? Because I see in the code you wrote that hdrplus has a higher "score" but is after the hdr because of regexp I guess.

**Comment by soloam** [comment]
You are correct, tks for the notice, I'll fix it

**Comment by soloam** [comment]
Done @denngie tks

**Pull request merged**
