### PR TITLE
update TPB to new TLD and search API

### PR DESCRIPTION
**Pull request by X-dark**
back to .se

### CODE REVIEW

**Comment by cvium** [comment]
Have you tested that it works? I get a RequestException because they seem to use cloudflare.

Plugin also needs to be updated to use new flexget search api.

**Comment by X-dark** [comment]
Yes it does work for me.
I have seen about the new search API warning. Where are the changes documented?

**Comment by cvium** [comment]
What is your config? It refuses to work for me because of SSL verification problems.

I am not sure about the specifics of the search API, but changing line 107 to `def search(self, task, entry, config=None):` and line 123 to `for search_string in entry.get('search_strings', [entry['title']]):` seems to do the trick.

**Comment by X-dark** [comment]
Nothing particular in my config
```
    discover:
      what:
        - emit_series:
            from_start: yes
      from:
        - piratebay:
            category: 208
            sort_by: seeds
```

I don't see how you can get SSL verification problem with an HTTP URI.

**Comment by cvium** [comment]
Maybe it's something Windows specific. But it definitely checks the SSL certificate. Anyway, if you fix the search api I think we can merge.

**Comment by cvium** [comment]
Great, thanks.

**Pull request merged**
