### PR TITLE
add vscode dev container to project

### PR DESCRIPTION
**Pull request by shadycuz**
### Motivation for changes:
vscode [devcontainers](https://code.visualstudio.com/docs/remote/containers) is one of the biggest steps forward in development and DevOps that I have ever seen. In my opinion it is bigger than Kubernetes or Terraform.

Unfortunately the documentation for the feature is a bit lacking. So let me explain. A devcontainer is just a docker container that has all the things needed for development already configured. Things like the correct version of python, the application and its dependencies and other tools like `pre-commit`. 

The magic is that if you are using vscode, then the IDE will run INSIDE the devcontainer. That means you will get really strong typing and intellesense as well as see errors/warnings from linting and formatting tools inside your IDE as you type. 

It's also make its super easy for vscode users to contribute to flexget. They just open it up in vscode and everything is setup for them. They can immediately run `pre-commit run -a` or `pytest` and everything will just work. Go ahead and try it for your self ;).

Note it does take a while to build the container the first time around. Thats mainly because I'm building pythons 3.7-3.10, because I plan to circle back with a follow up PR to add the ability to locally run the test suite against all supported versions of python. Since it's docker, it's only slow the first time around and then fast after that. 

Oh and I almost forgot to mention, I can send you some pipeline code that will allow you to run your Jenkins pipeline inside the devcontainer.

### Detailed changes:
- Added `.devcontainer` dir to hold the json config and dockerfile for the devcontainer.
- Added the `.devcontainer` and `.venv` directories to the docker and git ignore files.

### Addressed issues:
- Well at least now I'm ready to add new features.

### Implemented feature requests:
- N/A

### Config usage if relevant (new plugin or updated schema):
N/A
### Log and/or tests output (preferably both):
I let it finish, just verified things were working

#### To Do:
- [ ] If you are interested in this feature I will edit the development documentation to mention the devcontainer support.

### CODE REVIEW

**Comment by aidan-** [comment]
Awesome work, this greatly simplifies getting a dev environment up and running! 

I did a quick test locally and it all seems to be working.  I hit one issue running the `postCreateCommand` step due to the permissions/owner of the checked out repository vs the user inside the container:

```
vscode@783e012bef74:/workspaces/Flexget$ git status
fatal: unsafe repository ('/workspaces/Flexget' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/Flexget
```

It's an easy fix, but would it be better to use the same user id as the host user inside the container to prevent this issue?

**Comment by shadycuz** [comment]
@aidan- I'm not seeing this behavior on my machine. By default vscode will change the UID and GID to make the outside and the inside of the container match. To test this I changed the UID in the Dockerfile to `777` and then rebuilt the container.

You should see this process in the logs if you click it in the bottom right hand corner. 

image

Here is the relevant portion of my logs:
```
[1105153 ms] Start: Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.238.2 -t vsc-flexget-7b338eeeb8e766e3a7081687ecb51cc6-uid --build-arg BASE_IMAGE=vsc-flexget-7b338eeeb8e766e3a7081687ecb51cc6 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=vscode /tmp/vsch
[+] Building 20.8s (4/5)                                                        
 => [internal] load build definition from updateUID.Dockerfile-0.238.2     0.0s
 => => transferring dockerfile: 1.34kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/vsc-flexget-7b338eeeb8  0.0s
 => [1/2] FROM docker.io/library/vsc-flexget-7b338eeeb8e766e3a7081687ecb5  0.4s
 => [2/2] RUN eval $(sed -n "s/vscode:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\(  20.2s
 => => # Updating UID:GID from 777:777 to 1000:1000. 
 ```

On my machine this step took a really long time =/, mainly because I had a bunch of cache files and stuff already in my workspace.

Could you please run this command inside the devcontainer and outside? `echo $UID` They should match.

If they don't, then maybe its your version of vscode and the remote-container extension?
Are you on windows? I don't think the setting of UID and GID is supported on windows.

**Comment by aidan-** [comment]
I am running OSX with Rancher Desktop as my docker runtime.  I followed your instructions and modified line 4 of the Docker to change the UID to 777 and that's the value inside in container.  It looks like nothing is overriding it on my system. 

Inside the container
```
(.venv) vscode@59ff5a8d40f0:/workspaces/Flexget$ id
uid=777(vscode) gid=777(vscode) groups=777(vscode)
```

VScode Version: 1.68.1
Remote - Containers extension v0.238.3

I'll have a bit of a play - its likely something on my end and not specific to this configuration.

**Comment by shadycuz** [comment]
@aidan- You should raise an issue here https://github.com/microsoft/vscode-dev-containers/issues

I think it's a great feature that has no impact on people who don't use vscode.

Who is running the show these days? @gazpachoking?

Is Flexget interested in this feature? If so I have a few more tweaks from my work in #3481 that I would like to add to this PR.

**Comment by BrutuZ** [comment]
Will this affect my current environment or is it opt-in? I run a auto-updated git clone of flexget installed in a venv, and keep some changes that may or may not become PRs.

**Comment by shadycuz** [comment]
@BrutuZ It has 0 effects on any existing environments. It only takes effect if you open it inside your vscode IDE and then manually click "open in devcontainer".

**Comment by gazpachoking** [comment]
I don't use vscode, but I'm fine with this going in. 

> Is Flexget interested in this feature? If so I have a few more tweaks from my work in #3481 that I would like to add to this PR.

You want to add more commits here before merge? Or is this good to go?

**Comment by shadycuz** [comment]
@gazpachoking I want to add a few more commits 🚀

**Comment by aidan-** [comment]
@shadycuz are you still planning on getting this merged in?

**Comment by shadycuz** [comment]
@aidan- @gazpachoking 

Initially, I wanted to expand on this PR but I'm blocked on #3481, which is blocked by bugs in OMBI. We can merge this now and let people use it and provide feedback. When I complete my work in #3481, I will follow with a second PR with even more improvements to the dev container. 

Thanks for being patient =)

**Comment by paranoidi** [comment]
Great work! Thanks to everyone :)

**Comment by paranoidi** [comment]
Oh, updating dev docs would be good too. Otherwise this may be missed by ppl.

**Comment by shadycuz** [comment]
@paranoidi I was going to do but I didn't see a `CONTRIBUTING.md` file in the repo. I guess you are using the documentation on the flexget website? 

I can eventually update it, but for those using vscode, its going to prompt you to open in a devcontainer anyways. I still have some features I want to add, so I hope to improve on it in the future.

**Comment by paranoidi** [comment]
@shadycuz Development documentation is maintained in sphinx (https://flexget.readthedocs.io/en/latest/), the content for it is in the main repository.

**Pull request merged**
