### PR TITLE
Updated to use the download plugin

### PR DESCRIPTION
**Pull request by programatix**
I'm new to Python, so I'm not sure why the download will fail on private trackers. It gives the "maybe a login page" error.

I'm using the same config file I used on my router (with transmission plugin) and it failed. I'm currently running FlexGet on Windows. The task has form plugin.

### CODE REVIEW

**Comment by programatix** [comment]
I think I found out why the download failed. It seems that the urlrewrite is not working.

**Comment by programatix** [comment]
If i remove the usage of download plugin, url rewrite plugin will kick in. Help from experience flexget coder needed.

**Comment by gazpachoking** [comment]
Seems pretty good to me at first glance, is there something that is still not working as expected?

**Comment by programatix** [comment]
Everything is working fine.


Sent from my Samsung device

-------- Original message --------

**Pull request merged**
