### PR TITLE
Fix non-critical PassThePopcorn entry field comparison error

### PR DESCRIPTION
**Pull request by jtpavlock**
### Motivation for changes:

Fixes a non-critical error occurring when accessing one of the entry fields that is None-type. This was occurring for me when comparing a string to type None for example. 

### Detailed changes:
- Sets the default value for entries without values to be an empty string instead of None. This will remove any errors when trying to compare a string in the entry field.

### CODE REVIEW

**Comment by paranoidi** [comment]
Hmm, if the value is empty do we want to omit the field instead, I think this is how we generally have operated? Looks good otherwise.

**Comment by jtpavlock** [comment]
on the configuration side, there is no way to know if a field will be empty or not ahead of time. If you omit the field entirely and the someone attempts to access it in their config (I’m thing via regexp or if plug-in) wouldn’t that cause issues?

**Comment by liiight** [comment]
We generally not so this. Any entry field can be none and you should check for this in your jinja usage. I'm not saying its ideal, but it's what we use all around.

**Comment by jtpavlock** [comment]
I see. What’s a good way to check if an entry field is none before attempting to access it then?

**Comment by gazpachoking** [comment]
You can check if a field has a value in jinja with `{% if somefield %}` This will be false if somefield is None, or an empty string. If you want to also check if the field exists at all, you can do `{% if somefield is defined and somefield %}`. If you are just trying to turn a None into an empty string, you can do `{{ somefield|default('') }}`

**Comment by cvium** [comment]
Based on the discussion, I'll close this.

**Pull request closed without merging**
