### PR TITLE
Update guessit to 2.0

### PR DESCRIPTION
**Pull request by Toilal**
It's been a long time I didn't not performed a commit here but ...

I've rewriten guessit from scratch in version 2. Currently guessit 2 is in Beta, but it's working quite well and is far easier to maintain.

This PR should not be merged because it's a work in progress ! I'll let you know when it's ready :)

### CODE REVIEW

**Comment by gazpachoking** [comment]
@Toilal Something's wrong with the tests?

**Comment by Toilal** [comment]
Yes it's still a work in progress, I need to fix those tests. I hope i will
do this next week.
Le 20 nov. 2015 2:21 AM, "Chase Sterling" <notifications@github.com> a
écrit :

**Comment by gazpachoking** [comment]
Ahh, I see that now. Sorry about that.

**Comment by Toilal** [comment]
@gazpachoking I think it's ready to merge ! Maybe you could give it a try ?

**Comment by gazpachoking** [comment]
Does this allow us to re-enable any of the tests that we currently skip for guessit?

**Comment by Toilal** [comment]
Maybe... Which test are disabled? I didn't notice them, I could give a try.
Le 3 déc. 2015 5:14 AM, "Chase Sterling" <notifications@github.com> a
écrit :

**Comment by gazpachoking** [comment]
https://github.com/Flexget/Flexget/blob/3025c51455a6bbebb00e86c320613c652fb7b816/tests/test_qualities.py#L113
https://github.com/Flexget/Flexget/blob/3025c51455a6bbebb00e86c320613c652fb7b816/tests/test_seriesparser.py#L166

**Comment by Toilal** [comment]
No problem for `test_seriesparser`, but `test_qualities` has 3 invalid case :+1: 

```
AssertionError: 3 failures:
`Test.File.720hd.bluray` quality should be `720p bluray` not `bluray`
`Test.File.720p50` quality should be `720p` not `unknown`
`Test.File.truehd` quality should be `truehd` not `unknown`
```

I think I could enhance guessit 2 to support those cases.

**Comment by Toilal** [comment]
Ok I've rebased on current develop branch, and released a new guessit version to support failing test cases. All should be OK now !

**Comment by gazpachoking** [comment]
Should we wait for final 2.0 to come out?

**Comment by Toilal** [comment]
`2.0` final release will be the same. I'm only waiting more users feedbacks to go to final release, but it's actually working really fine.

**Comment by liiight** [comment]
Is this ready?

**Comment by Toilal** [comment]
I just released a new rc version for guessit. I'll rebase to solve the merge conflict. It's ready after that.

**Comment by Toilal** [comment]
Oops, some breaking changes here :) I need to fix this.

**Comment by Toilal** [comment]
Seems good to merge.

**Comment by gazpachoking** [comment]
Sounds good to me, thanks! (Stick around for any fallout though :wink:)

**Comment by alneven** [comment]
```
Plugin `flexget.plugins.parsers.parser_guessit` failed to import dependencies
No module named rules
```

after "git pull" I cannot start my config...

**Comment by Toilal** [comment]
Did you update your dependencies?

**Comment by alneven** [comment]
I'm doing it now :-D
I remembered it at the point I hit here the "comment" button
```
bin/pip install --upgrade -e .
```

**Comment by liiight** [comment]
@toilal what are the improvements with this version?

**Comment by Toilal** [comment]
This new version is a total rewrite of guessit. In most use cases, results will be exactly the same as guessit 1. Tests have been ported to the new version, and it was a main goal to keep the same results.

Internally it's totally changed, but for the user it's quite the same, but it's easier to extend and customize too.

It has been rewrite to make to code easier to read, and to fix some design issues that would have been impossible to fix without rewriting from scratch. For me as guessit developer, it's really easier to maintain, fix issues, implement new patterns and rules.

**Comment by liiight** [comment]
cool, nice work :+1:

**Comment by cvium** [comment]
I think this merge was a little premature. Subliminal has not been updated to support guessit2...

**Comment by Toilal** [comment]
Ho yes, so bad :(

I'll try to open a pull request on subliminal, @Diaoul is ready to go to this new version, but has some issues. https://github.com/Diaoul/subliminal/issues/550

**Comment by gazpachoking** [comment]
@Toilal I think we need to remove guessit from the global requirements, and make it just needed to load the specific plugin.There is the subliminal problem (#803), as well as requiring a c compiler now for dependencies (#815). I'd like all of our deps to stay installable with pure python, and any that aren't be optional.

**Comment by Toilal** [comment]
Ok, no problem. I'll try to avoid usage of [regex module](https://pypi.python.org/pypi/regex) in a near future, and help subliminal to switch to guessit 2. I'll let you know when all is over :)

**Comment by Toilal** [comment]
See guessit-io/guessit#257

**Comment by Toilal** [comment]
I've released a new guessit rc version that makes the regex module optional. So it's now pure python by default, but still possible to use regex module by manually install it or enabling the "native" extra with pip.

I also plan to help subliminal to quickly go for guessit 2 now.

**Comment by stevezau** [comment]
@Toilal should we update the req's for the new guessit RC?

**Comment by Toilal** [comment]
`guessit>=2.0.1` will be perfect.

**Comment by Toilal** [comment]
It's now officialy released

**Comment by liiight** [comment]
Did the subliminal issue get fixed?

**Comment by Toilal** [comment]
No, but Pull Request is ready to merge on subliminal repository. Then ask
@Diaoul for a release and we are fine :)

**Pull request merged**
