### PR TITLE
Update NPO_watchlists tests

### PR DESCRIPTION
**Pull request by mfonville**
### Motivation for changes:
The NPO website had some changes; updated the tests to reflect this

### CODE REVIEW

**Comment by mfonville** [comment]
I don't know why CircleCI failed, it seems as if it has not applied the first of the two commits for running the tests on the updated cassettes?

Locally all the tests do pass :-/

**Comment by mfonville** [comment]
Re-ran the tests and cassettes, now it seems to be ok

**Comment by mfonville** [comment]
Could this (trivial) update to the tests please be merged; my server runs with every NPO-website these tests to check for any regressions, so having working tests greatly helps ;-)

**Comment by gazpachoking** [comment]
Yep, looks good to me.

**Pull request merged**
