### PR TITLE
Fix for "UnboundLocalError: local variable 'r' referenced before assi…

### PR DESCRIPTION
**Pull request by planeturban**
…gnment"

Return blank entries list instead of crashing when failing to fetch rss.

### Motivation for changes:
fill_entries_for_url() keeps crashing when nzb.su have intermittent problems. 

### Detailed changes:
````
        try:
            r = task.requests.get(url)
        except RequestException as e:
            log.error("Failed fetching '%s': %s" % (url, e))

        rss = feedparser.parse(r.content)
````  
Since r never gets defined with the try block I've added an else to the block to keep it from crashing. It'll return a blank entry list instead.

### Addressed issues:
- Fixes crash.

### Implemented feature requests:
N/A
### Config usage if relevant (new plugin or updated schema):
N/A

### Log and/or tests output (preferably both):
N/A (It doesn't crash anymore. :) )
#### To Do:
Nothing

### CODE REVIEW

**Comment by planeturban** [comment]
I'll merge this in a couple of days, after real-life tests has been run for more than 30 minutes. :)

(If no one minds, that is.)

**Comment by gazpachoking** [comment]
Looks good to me 👍

**Comment by paranoidi** [comment]
PR needs refreshing after logging upgrade.

**Comment by planeturban** [comment]
Done and done. Merging.

**Pull request merged**
