### PR TITLE
Replace obsoleted and unmaintaned transmissionrpc

### PR DESCRIPTION
**Pull request by rsekman**
### Motivation for changes:

[`transmissionrpc`](https://pypi.org/project/transmissionrpc/) is unmaintained. Swap to [`transmission-rpc`](https://pypi.org/project/transmission-rpc/) as suggested in #2727.

### Detailed changes:

Drop-in replacement of imports.
The newer `transmission-rpc` does not provide `HTTPHandlerError`. Instead it raises exceptions from `requests.exceptions`. Error handling on connecting to transmission has to be changed accordingly.

### Addressed issues:
-  #2727  .

### Possible improvements

Error handling could be more fine-grained, but `requests.exceptions` are very detailed as they are.

### CODE REVIEW

**Comment by gazpachoking** [comment]
Excellent, looks good to me. Thanks!

**Comment by ksurl** [comment]
From_transmission is not working. See error [here](https://github.com/Flexget/Flexget/issues/2794).

**Comment by mfonville** [comment]
The pip dependencies have not been updated to reflect this change. Users miss the `transmission-rpc` library and get an error:
`CRITICAL transmission  xxx  transmission-rpc module version 0.11 or higher required.`

**Comment by BrutuZ** [comment]
`transmission-rpc` is an optional dependency like many others. Flexget warns it's required when you call a plugin that needs it, the rest is up to you

**Comment by mfonville** [comment]
True that the dependency is optional. So I was wrong to mention it as a pip-dependency.
But users get now when upgrading their Flexget no explicit notice that this dependency has changed. And when executing Flexget and receiving that critical error, I have doubts whether they notice the extra dash in `transmission-rpc` and understand that it is different from the package they have installed in the past.

Maybe an explicit error if `transmissionrpc` has been found but no `transmission-rpc` could help them.

**Comment by ksurl** [comment]
I've added it to the [Upgrade Actions page](https://flexget.com/UpgradeActions)

**Comment by Karlson2k** [comment]
@gazpachoking, could you please look into related issue https://github.com/Flexget/Flexget/issues/2794?

**Pull request merged**
