### PR TITLE
Fix pyload plugin

### LINKED ISSUE #1136: Failed by payload plugin because 91
2016-05-04 17:43 VERBOSE  task *** FAILED: `***` by pyload plugin because 91

### PR DESCRIPTION
**Pull request by cvium**
### Motivation for changes:
Beats me
### Detailed changes:

- Messy plugin. Tried making it prettier/better.
- Use json.dumps to make sure every post parameter is properly formatted.
- Changed the schema to make sense (`pyload: yes`???)

### Addressed issues:

- Fixes #1136

### CODE REVIEW

**Comment by Roburetto** [comment]
I may have found an issue, related with  this particular commit or perhaps prior.

The thing is, while using parse_url most hosters have their urls correctly identified but not MegaCoNz.

I really know nothing of Python, but may be related with [the way the class is defined.](https://github.com/pyload/pyload/issues/2592#issuecomment-246205522)

**Comment by cvium** [comment]
This particular "commit" is a PR that has not been merged, so unless you're actually using this, this is the wrong place.

**Comment by Roburetto** [comment]
I am using it. I downloaded and replaced the file.

**Comment by cvium** [comment]
I don't agree with his assessment. https://github.com/pyload/pyload/wiki/module.Api.Api

```
Parses html content or any arbitaty text for links and returns result of checkURLs
```
That is what we use.

**Comment by Roburetto** [comment]
It seems Flexget does use [PyLoad's "parseURLs" API ability.](https://github.com/pyload/pyload/wiki/module.Api.Api)

parseURLs([html, url])	Parses html content or any arbitaty text for links and returns result of checkURLs.

So Flexget does send the URL to PyLoad for it to recognize hoster links...

**Comment by Roburetto** [comment]
OK. Thanks for confirming that. I will [return the issue to PyLoad.](https://github.com/pyload/pyload/issues/2592) then.

**Pull request merged**
