### PR TITLE
A pipe now splits all show type commands

### PR DESCRIPTION
**Pull request by sean797**
This allow me to nicely pipe the output through other programs when some text in columns are too big - often the case with "flexget plugins".

### CODE REVIEW

**Comment by nikdoof** [comment]
I don't think this solves your use case. I still have cutting on some commands.

```The Daily Show / 2014-09-10 / Jeremy Renner [720p / x264 / WEBRi |tv   ```

If you want a parsable output then really it should be a extra flag/option on the CLI, then you can forgo trying to format any of the data and essentially spit out a pipe delimited output, or you could switch all the output to use something like ```prettytable``` or ```tabulate``` to do the formatting and sizing for you.

**Comment by sean797** [comment]
What command did you give to get that output? 
I disagree about it should be a extra flag/option. Having a table with pipe's between columns cause no issues, only makes the output easier to read.

The reason of this commit is I'm writing a bash completion script and enables me to tab complete commands like "flexget doc" with the output of "flexget plugins | awk -F '|' '/--doc/{print $1}'". If you have a better way of doing it let me know?

**Comment by gazpachoking** [comment]
I think a better api is a nicer solution than trying to change cli options to be machine readable. It's something we are working on in the rest_api branch right now.

**Comment by paranoidi** [comment]
It's pretty common in cli apps to provide machine parseable output with argument. At least sometimes referred porcelain or so.

**Comment by sean797** [comment]
I've created a new pull request with --porcelain option on some commands. Using an api to get the data I need for bash completion purposes wouldn't work that well as it will require the daemon be running, some people use cron and don't run Flexget as a service.

**Comment by gazpachoking** [comment]
#574 merged

**Pull request closed without merging**
