### PR TITLE
NPO parameter has changed for only showing full episodes

### PR DESCRIPTION
**Pull request by mfonville**
### Motivation for changes:
NPO API has changed

### Detailed changes:

- What used to be e.g. http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?category=broadcasts is now http://www.npo.nl/als-de-dijken-breken/VPWON_1261083/search?media_type=broadcast

### Addressed issues:

- Without this fix, also other video objects, like small snippets of episodes are fetched

### CODE REVIEW

**Comment by liiight** [comment]
You forgot to redo cassettes

**Comment by mfonville** [comment]
I lack at the moment (access) to a system to re-run the cassettes on :-/
If somebody else could run them, I'd really appreciate it. Otherwise it will have to wait awhile I fear

**Comment by mfonville** [comment]
Another I noticed now, is that the testcase also needs an update.
Because it assumed the Trailer was the first season of the series, while in reality it wasn't (I just hadn't discovered yet that the parameter had changed; I only found that out just now, while toying a bit with the HTML and URLs)

**Comment by mfonville** [comment]
I now at least updated the test-case; so if somebody could just re-run the test an update the cassette from that run, it should be good to go

**Comment by mfonville** [comment]
Ok, I got hold of a machine for a moment where I could run the test and update the cassettes

**Pull request merged**
