### PR TITLE
 Multiples changes for t411 domain name change : from .ai to .al

### PR DESCRIPTION
**Pull request by poulpito**
According to t411 website : 
Il faudra donc tout faire passer du .ai au .al
L'adresse du site est https://www.t411.al/  (à mettre en favoris) 

Commit modify both plugins : api_t411 (+tests) and torrent411

### CODE REVIEW

**Comment by liiight** [comment]
Torrent411 is deprecated and will be removed in next minor release, so there's little point to fixing it...

**Comment by poulpito** [comment]
Could you dispatch commit file or do i need to push a new PR without the old plugin ? (still in use btw)

**Comment by liiight** [comment]
I really don't see a reason to have both of this plugins co exist. Is there functionality missing from the new plugin?

**Comment by ProphecyKt** [comment]
@liiight i already answer to that question in my last pull request #1777.
The new plugins doesn't work properly and it's incomplete (exemple : differents categories with the same name)
The ancient plugin is just an urlrewritter but it work very well. It's simple.

**Comment by liiight** [comment]
Right, forgot about that.

**Pull request merged**
