### PR TITLE
Remove GPLed code from rtorrent implementation

### LINKED ISSUE #2196: rtorrent SCGI transport looks like GPLed code with its license stripped
The [SCGI XML-RPC transport used in Flexget](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/rtorrent.py#L99-L224) looks exactly like the GPLed one that's floating around. An example of this can be seen [here](https://github.com/TinyHTPC/xbmc-dev-repo/blob/a3184d3f9451b23865bcf1abce380099f9367876/script.service.audo/resources/SickBeard/lib/rtorrent/lib/xmlrpc/scgi.py) or [here](https://gist.github.com/query/899683/7e5d0c123cd5a6117b3e3d0a9d41a583260516fd)

This also matches my experience looking for a better licensed SCGI Transport back in start of 2015 (before this code was added to Flexget) which resulted in me writing my own transport as none existed.

I suggest replacing the plagiarized SCGI Transport with [my own version](https://github.com/JohnDoee/autotorrent/blob/develop/autotorrent/scgitransport.py) as it should have no license issues and be functionally equivalent.

### PR DESCRIPTION
**Pull request by gazpachoking**
### Motivation for changes:
SGCITransport implementation was GPLed code. See #2196 This is hopefully just to inspire somebody to finish this job, as I haven't installed rtorrent or tested anything. Somebody with rtorrent can use this as a jumping off point for testing.

### Addressed issues:
- Fixes #2196 

#### To Do:
- [ ] Actually test it, probably fix some stuff.

### CODE REVIEW

**Comment by paranoidi** [comment]
Unfortunately does not work.

`
BUG: Unhandled error in plugin rtorrent: unsupported XML-RPC protocol
Traceback (most recent call last):
  File "/home/paranoidi/apps/flexget/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/home/paranoidi/apps/flexget/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/paranoidi/apps/flexget/flexget/plugins/clients/rtorrent.py", line 445, in on_task_output
    session=task.requests)
  File "/home/paranoidi/apps/flexget/flexget/plugins/clients/rtorrent.py", line 223, in __init__
    self._server = sp(self.uri)
  File "/home/paranoidi/apps/flexget/flexget/plugins/clients/rtorrent.py", line 164, in create_proxy
    return xmlrpc_client.ServerProxy(url)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1398, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol
`

**Comment by gazpachoking** [comment]
@paranoidi I may have fixed that issue

**Comment by paranoidi** [comment]
Re-testing

**Comment by gazpachoking** [comment]
@paranoidi confirmed this working, open up another ticket if someone finds more issues.

Thanks @johndoee

**Pull request merged**
