### PR TITLE
[WIP] search plugin for rarbg

### PR DESCRIPTION
**Pull request by cvium**
RarBG seems pretty decent and while their releases also float around on Torrentz etc. I think their site is a lot less noisy.

One thing though. They have some weird bot detection. If the cookie does not contain `'7fAY799j': 'VtdTzG69'`, then it will get caught by the bot filter after the ~5th consecutive request.

I'm not entirely sure they'd appreciate this plugin then, but their RSS feed sucks. Their anti-bot captcha is also extremely easy to circumvent with OCR.

### CODE REVIEW

**Comment by rarbg** [comment]
Hey :) Will a json api search work better ?

**Comment by cvium** [comment]
Possibly. There are two kind of feeds I usually use. A continuously updated <category> rss feed and search specific rss feeds.

I believe KAT employs an XML search API eg. https://kickass.to/usearch/the%20walking%20dead/?rss=1.

But any publicly available search API that allows querying on categories, seeds etc. would be a welcome addition.

**Comment by rarbg** [comment]
https://rarbg.com/pubapi/apidocs.txt
That looks fine to you ? I didnt have enough time to make it into something proper but should have everything you want ?

**Comment by cvium** [comment]
It looks pretty good. I don't know what "The api has a 1req/min limit." means though.

**Comment by rarbg** [comment]
1 request per minute max :)

**Comment by cvium** [comment]
Ah. Quite a big limitation though. Not sure it will be of much use with Flexget. It will be fine for simple RSS downloading eg. watching the TV/Movie rss feed every hour.
It won't be of much use for direct searching though.

**Comment by rarbg** [comment]
lowered the time to 1req/10s. That should be fine for searching ?

**Comment by cvium** [comment]
Yeah, that'll work. I will rewrite my plugin when I get some time.

**Comment by cvium** [comment]
Would it be possible to get magnet and .torrent options?

**Comment by rarbg** [comment]
We cant really implement .torrent because of many reasons which i cant discuss over github :(

**Comment by gazpachoking** [comment]
This still a WIP, or good to go?

**Comment by cvium** [comment]
WIP. Been pretty swamped lately and their API is a little funky. I'll merge it when I get it done :P

**Comment by gazpachoking** [comment]
@cvium Can you add this to the http://flexget.com/wiki/Searches page?

**Comment by cvium** [comment]
@gazpachoking Done.

**Comment by cvium** [comment]
@rarbg Would it be possible to search for specific episodes using tvdb or imdb ids? As it stands, older items can never be found if they are not within the latest 100 uploads.

**Comment by rarbg** [comment]
@cvium 
From the api docs - The api searches only in the last 10000 torrents except for imdb,tvrage,tvdb.
Meaning if you use the parameteres search_imdb=xxxx / search_tvrage=xxxx / search_tvdb=xxxx you will be able to search in all the old uploads. 
example:
pubapi.php?mode=search&search_imdb=tt0944947&search_string=Game+Of+Thrones+S03E03&token=xxxx

**Comment by cvium** [comment]
@rarbg  This one fails though: pubapi.php?mode=search&search_imdb=tt1839578&search_string=Person%20of%20Interest%20S02E01&token=gin6q1rtm0

but https://rarbgmirror.com/torrents.php?search=person+of+interest+s02e01 returns results.

**Comment by rarbg** [comment]
@cvium 
you need to read the docs :)

by default the api will return only ranked torrents ( internal ) ex scene releases + -rarbg releases + -rartv releases.
If you want other groups included in the results use the ranked parameter with a value of 0 to get them included.

**Comment by cvium** [comment]
@rarbg You are right, I wasn't thinking. Thanks for the clarification. All is well. I also see you have fixed min_seeders and min_leechers.

**Comment by rarbg** [comment]
@cvium yes they are fixed a long time ago :)

**Pull request merged**
