### PR TITLE
Merged web qualities, closes #1218

### LINKED ISSUE #1218: "web" is ignored as a quality
### Expected behaviour:

quality should be parsed as webrip

### Actual behaviour:

quality is parsed as '720p h264'

### Steps to reproduce:
- Step 1: ...

`flexget inject 'Powers.US.S02E01.720p.WEB.h264-DEFEATER' --task tv --dump`

#### Config:
```
series:
  tv:
    - Powers: {quality: <1080p webrip+}
```

  
#### Log:
```
2016-06-01 14:18 VERBOSE  series        tv             Ignored `Powers.US.S02E01.720p.WEB.h264-DEFEATER`. Does not meet quality requirement `<1080p webrip+`.

-- Undecided: --------------------------
title            : Powers.US.S02E01.720p.WEB.h264-DEFEATER
url              : http://localhost/inject/Gj8wRPBIkxmcu9gTtl3N2WYVzif5SL
original_url     : http://localhost/inject/Gj8wRPBIkxmcu9gTtl3N2WYVzif5SL
path             : ~/video/series/Powers/
proper           : False
proper_count     : 0
quality          : 720p h264
release_group    : None
series_episode   : 1
series_episodes  : 1
series_id        : S02E01
series_id_type   : ep
series_name      : Powers
series_parser    : <SeriesParser(data=Powers.US.S02E01.720p.WEB.h264-DEFEATER,name=Powers,id=None,season=2,episode=1,quality=720p h264,proper=0,status=OK)>
series_releases  : [91146]
series_season    : 2
task             : tv
```

### Additional information:

- Flexget Version: 2.0.38
- Python Version: 2.7.11
- Installation method: git
- OS and version: OS X

### PR DESCRIPTION
**Pull request by cvium**
### Motivation for changes:
Webrip quality has improved greatly over the last few years to the point where it's even better than hdtv. Quality is known as `webrip` or `web` (scene), but some p2p groups also call it `web-dl` (although technically, `web-dl` refers to something like iTunes download).

Qualities is in need of an overhaul, but this small change would help immensely until then.

### CODE REVIEW

**Comment by alneven** [comment]
when will be this LIVE?

I tried to add Quality "webdl" and "webrip", but I had issues, then I came to this commit, as it should be merged as "web", but it's not working yet.


Some logs:
2017-01-01 20:19 CRITICAL manager                       [/tasks/get_favtvshowshd/series/0/Homeland/quality] Got `[u'720p webdl h264 dd5.1', u'720p webrip h264 dd5.1']`, expected: string
2017-01-01 20:19 CRITICAL manager                       [/tasks/get_favtvshowshd/series/1/The Walking Dead/quality] Got `[u'1080p webdl h264 dd5.1', u'1080p webrip h264 dd5.1']`, expected: string

2017-01-01 20:25 CRITICAL manager                       [/tasks/get_favtvshowshd/series/0/Homeland/quality] web is not a valid quality component.
2017-01-01 20:25 CRITICAL manager                       [/tasks/get_favtvshowshd/series/1/The Walking Dead/quality] web is not a valid quality component.



In the CONFIG:
      - Homeland:
          set:
            tvdb_id: 247897
          quality: 720p webdl h264 dd5.1


I had "webdl", but the new NTb release is a webRIP
Which doesn't match the quality expectations

So, I have added 
quality:
  - 720p webdl h264 dd5.1
  - 720p webrip h264 dd5.1

But it doesn't worked for me

Not even with "xxx"

**Comment by alneven** [comment]
I'm under "2.8.15.dev"

**Comment by cvium** [comment]
I'm not sure what you mean. Your config is not valid as the log aptly states. `webrip` is an umbrella term for `web` and `webrip`. 

If you want to accept `web`, then `webrip` is what you should put in your config.

**Comment by alneven** [comment]
I had to add
720p webdl|webrip h264 dd5.1
to get this working...

**Comment by alneven** [comment]
I thought you added
webrip and webdl
as one quality called "web"


but not than... sorry

**Comment by cvium** [comment]
It was reverted.

**Pull request merged**
