### PR TITLE
Bugfix for 'cannot import name path' with path.py 8.0

### PR DESCRIPTION
**Pull request by thalamus**
The update to path.py removes the lowercase path alias which flexget relies on
Simply change it to use 'Path' instead of 'path.

http://flexget.com/ticket/3064

### CODE REVIEW

**Comment by gazpachoking** [comment]
Awesome, thanks!

**Comment by gazpachoking** [comment]
Maybe we should also update our requirements to say path.py >= 6.2 (the version where the upper case was introduced.)

**Comment by thalamus** [comment]
Yeah, I've just done a commit for that, I'll open a pull request for it :)

**Comment by thalamus** [comment]
There's quite a few unhappy people on that path bug: https://github.com/jaraco/path.py/issues/102
Looks like the change has broken a lot of code and it seems to have caused a bit of a fuss.

**Comment by antivirtel** [comment]
You can still commit to this Branch, you don't need to open a new one!

**Pull request merged**
