### PR TITLE
Fixes imdb changes introduced 2016-01-26

### PR DESCRIPTION
**Pull request by m-hume**
The movie title H1 tag no longer contains a span with itemprop='name'
the H1 tag has an attribute itemprop='name'

fixes https://github.com/Flexget/Flexget/issues/824

### CODE REVIEW

**Comment by lepinkainen** [comment]
You need to update the cassettes to make the tests work again, since there was a layout change on IMDB.

**Comment by stevezau** [comment]
Thanks, i'll update the cassettes.

**Comment by m-hume** [comment]
Thanks for tidying up for me guys!
Just wanted to get the fix in before i went out for dinner with my granddad (96)
Will do it properly next time!

**Comment by stevezau** [comment]
@m-hume there are several tests failing.. i'm making more changes so it will be a little while.

**Comment by msj33** [comment]
Any update?

**Comment by crawln45** [comment]
Should have been pushed to master last night

**Comment by liiight** [comment]
It's in. Verify upgrade

**Comment by msj33** [comment]
Working here again with latest(todays) release - thanks for quick help - Much appreciated:-)

**Pull request merged**
