### PR TITLE
[add] torznab: More complete RSS XML entry data

### PR DESCRIPTION
**Pull request by rpatterson**
### Motivation for changes:
I needed access to the `size` child of the RSS `<item>` element like the `rss`
input plugin provides.

### Detailed changes:
While trying to address that I noticed what seemed
like an unnecessarily limited and hard-coded approach to extracting the
`<item>` elements children, so this change implements a more generalized
approach.

I would like to use a more generalized approach for the `<torznab:attr>`
children as well.  The current implementation is, however, sufficient for now
and ripping that out would be more invasive.

In fact, I'd love to see FlexGet use something like
[`xmltodict3`](https://github.com/dart-neitro/xmltodict3) wherever data is
being extracted from XML and inserted into entries so that using RSS or other
XML in FlexGet is consistent throughout.

### CODE REVIEW

**Comment by rpatterson** [comment]
I noticed [this same CI error](https://github.com/Flexget/Flexget/runs/3270932270) when trying to set up local development:

```
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8
```

That package isn't needed nor available for Python 3.7+, so I don't think those failures are related to this PR and I'm sue it's a known issue.

**Comment by rpatterson** [comment]
> This PR is stale because it has been open 150 days with no activity. Remove stale label or comment or this will be closed in 60 days.

I'm still waiting for a response to [my question about the CI failures](https://github.com/Flexget/Flexget/pull/3118#issuecomment-894709450).

**Comment by gazpachoking** [comment]
> I'm still waiting for a response to [my question about the CI failures](https://github.com/Flexget/Flexget/pull/3118#issuecomment-894709450).

Hmm, sorry about that. I'm not sure what would be going wrong there. Can you try rebasing or merging in current develop and seeing if it happens again? Seems like this is too old for me to see the test results.

**Comment by rpatterson** [comment]
> Hmm, sorry about that. I'm not sure what would be going wrong there. Can you try rebasing or merging in current develop and seeing if it happens again? Seems like this is too old for me to see the test results.

Thanks for the followup!  I'm not sure when I'll be to get around to that, but I'll let you know when/if I do.

**Pull request closed without merging**
