### PR TITLE
Add verify_ssl option to rss plugin.

### PR DESCRIPTION
**Pull request by Ram-Z**
This option allows to disable SSL Cert Verification.

### CODE REVIEW

**Comment by Ram-Z** [comment]
Just saw there is a `verify_ssl_certificates` plugin which does the same on a per task basis.

This PR allows a more fine grained control over which SSL certs should be verified by adding an option to each instance of an `rss` setting. But feel free to close this unmerged it you feel it's not necessary.

**Comment by cvium** [comment]
Tests using RSS are failing.

**Comment by Ram-Z** [comment]
Fixed, I always forget that setting the default value in the schema is not sufficient to pass the tests.

**Comment by gazpachoking** [comment]
I think verify_ssl_certificates plugin is good enough. If we need per-plugin control I'd like to think of a system better than adding this option to every single plugin.

**Pull request closed without merging**
