### PR TITLE
AlphaRatio category mapping update

### LINKED ISSUE #2502: Missing categories from Alpharatio plugin
### Expected behaviour:

Alpharatio plugin support all categories listed on website

### Actual behaviour:

Task fails when using missing category

### Steps to reproduce:

Run task with categories missing (TvUHD, TvPackUHD, MovieUHD, MoviePackUHD)

#### Config:
```yaml
tasks:

  search-tv:
    priority: 2
    template:
      - global-settings
      - tv-settings
    discover:
      what:
        - next_series_episodes: yes
      from:
        - alpharatio:
            <<: *alpharatio_credentials
            category: TvHD, TvUHD
        - iptorrents: 
            <<: *iptorrents_credentials
            category: [22, 5, 99]
        - torrentleech: 
            <<: *torrentleech_credentials
            category: [32]
      interval: 3 hours
    cfscraper: yes

  search-movies:
    priority: 3
    template:
      - global-settings
      - movie-settings
    discover:
      release_estimations:
        optimistic: 30 days
      what:
        - movie_list: Movies
      from:
        - alpharatio:
            <<: *alpharatio_credentials
            category: MovieHD, MovieUHD
        - torrentleech: 
            <<: *torrentleech_credentials
            category: [14, 37, 47]
        - iptorrents: 
            <<: *iptorrents_credentials
            category: [48, 20, 100, 101]
      interval: 3 hours
    cfscraper: yes
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

[/tasks/search-tv/discover/from/0/alpharatio/category] Must be one of the following: tvsd, tvhd, tvdvdrip, tvpacksd, tvpackhd, moviesd, moviehd, moviepacksd, moviepackhd, moviexxx, mvid, gamespc, gamesxbox, gamesps3, gameswii, appspc, appsmac, appslinux, appsmobile, 0dayXXX, ebook, audiobook, music, misc

</details>

### Additional information:

Missing categories are:
TvUHD, TvPackUHD, MovieUHD, MoviePackUHD

- FlexGet version: 3.0.4
- Python version: Python 3.7.5
- Installation method: Docker wiserain/flexget:latest
- Using daemon (yes/no): yes
- OS and version:
- Link to crash log:

### PR DESCRIPTION
**Pull request by metaMMA**
### Motivation for changes: 
Github issue.

### Detailed changes:
- updated AlphaRatio category mapping

### Addressed issues:
- Fixes #2502

### CODE REVIEW

**Comment by gazpachoking** [comment]
Hmm, it's a shame these mappings changed for existing categories. This means that somebodies config could break next time they change the categories. I guess it shouldn't block this PR, but it would be nice to find a way to have that mapping be constant, so next time they change it it doesn't invalidate the categories that still exist.

**Comment by frankyw** [comment]
Well it does say in the [config example](https://flexget.com/Searches/alpharatio) to use the category names vs numbers, which is what I (and hopefully most others) did, so it should be fine. 

If people used numeric identifiers and AR changed their numeric identifiers, not much we can do about that tbh.

If we can merge this, that would appreciated.

**Comment by metaMMA** [comment]
@gazpachoking I think their plugin would have been broken directly after the mapping change, because their config category values were/are being mapped to the wrong AR category numbers we have in this plugin. I'm not sure when they were changed, though.

I'll setup a web trigger to send me an email if the mappings change again.

**Comment by gazpachoking** [comment]
> I think their plugin would have been broken directly after the mapping change, because their config category values were/are being mapped to the wrong AR category numbers we have in this plugin

Agreed, that's what I was wondering if we could find a fix for.

I'll merge this now, if we can find some better solution we can deal with it in a future PR.

**Pull request merged**
