### PR TITLE
Config packagePassword added

### PR DESCRIPTION
**Pull request by kasperj**
Plugin gained the option to send a predefined password for a package to pyload.

### CODE REVIEW

**Comment by gazpachoking** [comment]
Our standard for variable naming both in code and config is normally to use underscores rather than camel case. i.e. `package_password` rather than `packagePassword`
Otherwise I'll just trust you that this is an useful thing, as I know nothing of pyload. :wink:

**Comment by kasperj** [comment]
Fixed the naming, didn't know about your style, pyload extracting is quite buggy at the moment, adding a password to the package makes the extracting much more stable

**Comment by gazpachoking** [comment]
Thanks, want to update the wiki?

**Comment by kasperj** [comment]
Sure, how to do that? :P

**Comment by liiight** [comment]
http://flexget.com/wiki/Plugins/pyload
login and edit :smile:

**Pull request merged**
