### PR TITLE
Correction IMDb login fails #1321

### LINKED ISSUE #1321: IMDb login fails
### Expected behaviour:
imdb_list plugin logins in successfully with the logged in credentials.

### Actual behaviour:
Login fails.

### Steps to reproduce:
- Step 1: excute configuration

#### Config:
```
tasks:
  testtask:
    rss: <feed>
    imdb_lookup: yes
    list_match:
      from:
        - imdb_list:
            login: <username>
            password: <password
            list: watchlist
    download: <dir>
```

#### Log:
```
2016-08-08 20:26 VERBOSE utils.requests testtask Waiting 3.83 seconds until next request to imdb.com
2016-08-08 20:26 VERBOSE utils.requests testtask Waiting 4.66 seconds until next request to imdb.com
2016-08-08 20:26 CRITICAL plugin testtask Login to IMDB failed. Check your credentials.
2016-08-08 20:26 WARNING task testtask Aborting task (plugin: list_match)
```

### Additional information:
liiight advies to raise a ticket. Test was done by Krozer.
- Flexget Version: 2.2.13
- Python Version: 2.7.11
- Installation method: pip
- OS and version: Mac OS X 10.11.6
- Link to crash log:

### Test done by Krozer:
```
import re
import pprint

from flexget.utils.requests import Session as RequestSession, TimedLimiter
from requests.exceptions import RequestException
from flexget.utils.soup import get_soup
from flexget.plugin import PluginError


pp = pprint.PrettyPrinter(indent=4)
_session = RequestSession()
_session.add_domain_limiter(TimedLimiter('imdb.com', '5 seconds'))
_session.headers = {'Accept-Language': 'en-us'}

try:
	r = _session.get(
		'https://www.imdb.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-'
		'handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&'
		'openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%'
		'2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.ope'
		'nid.net%2Fauth%2F2.0')
except RequestException as e:
	raise PluginError(e.args[0])
	
soup = get_soup(r.content)
inputs = soup.select('form#ap_signin_form input')
data = dict((i['name'], i.get('value')) for i in inputs if i.get('name'))
action = soup.find('form', id='ap_signin_form').get('action')
pp.pprint(action)


data['email'] = <email>
data['password'] = <password>
print('email=%s, password=%s', data['email'], data['password'])


d = _session.post(action, data=data)
# Get user id by extracting from redirect url
r = _session.head('http://www.imdb.com/profile', allow_redirects=False)
pp.pprint(r.headers)
if not r.headers.get('location') or 'login' in r.headers['location']:
	raise PluginError('Login to IMDB failed. Check your credentials.')
user_id = re.search('ur\d+(?!\d)', r.headers['location']).group()
cookies = dict(d.cookies)
```

### PR DESCRIPTION
**Pull request by krozer**
### Motivation for changes:
	Correction IMDb login fails
### Detailed changes:

use _session.headers.update to not overwrite header.

add _session.headers.update({reference : http://...}) For better browser simulation
and also post the URL from the action attribute of the form.

### Addressed issues:

- Fixes #1321

### Config usage if relevant (new plugin or updated schema):
```
tasks:
  import_from_imdb:
    imdb_lookup: yes
    imdb_list:
      login: ********
      password: ********
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: from_imdb


```
### Log and/or tests output (preferably both):
```
2016-08-12 15:31 DEBUG    task          import_from_imdb executing import_from_imdb
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb fetching items from IMDB
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb user credentials not found in cache or outdated, fetching from IMDB
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching https://www.imdb.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb email=***********, password=**********
2016-08-12 15:31 VERBOSE  utils.requests import_from_imdb Waiting 3.40 seconds until next request to imdb.com
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching https://www.imdb.com/ap/signin/151-8146494-9510128?ie=UTF8&pf_rd_r=0JEHNJ78AQWGZCRQWDP7&pf_rd_m=A2A1PIL045UJ9G&pf_rd_t=6301&pf_rd_i=imdb_mobile_us&pf_rd_p=2187562082&pf_rd_s=mobile-signin-slot
2016-08-12 15:31 VERBOSE  utils.requests import_from_imdb Waiting 4.51 seconds until next request to imdb.com
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching http://www.imdb.com/profile
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb could not find list ID in cache, fetching from IMDB
2016-08-12 15:31 VERBOSE  utils.requests import_from_imdb Waiting 4.67 seconds until next request to imdb.com
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching http://www.imdb.com/list/_ajax/watchlist_has
2016-08-12 15:31 VERBOSE  utils.requests import_from_imdb Waiting 4.75 seconds until next request to imdb.com
2016-08-12 15:31 DEBUG    utils.requests import_from_imdb Fetching http://www.imdb.com/list/export?list_id=ls063643555&author_id=ur68256787
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb parsing line from csv: 1, tt1386697, Sun Aug  7 00:58:27 2016, Sun Aug  7 00:58:27 2016, , Suicide Squad, Feature Film, David Ayer, , 7.0, 123, 2016, action, adventure, comedy, sci_fi, 110719, 2016-08-01, http://www.imdb.com/title/tt1386697/
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb parsing line from csv: 2, tt4196776, Sun Aug  7 00:58:31 2016, Sun Aug  7 00:58:31 2016, , Jason Bourne, Feature Film, Paul Greengrass, , 7.1, 123, 2016, action, thriller, 38574, 2016-07-11, http://www.imdb.com/title/tt4196776/
2016-08-12 15:31 DEBUG    imdb_list     import_from_imdb parsing line from csv: 3, tt2660888, Sun Aug  7 00:58:32 2016, Sun Aug  7 00:58:32 2016, , Star Trek: Sans limites, Feature Film, Justin Lin, , 7.5, 122, 2016, action, adventure, sci_fi, thriller, 52763, 2016-07-20, http://www.imdb.com/title/tt2660888/
2016-08-12 15:31 DEBUG    backlog       import_from_imdb 0 entries purged from backlog
2016-08-12 15:31 VERBOSE  details       import_from_imdb Produced 3 entries.
```

### CODE REVIEW

**Comment by paranoidi** [comment]
Oh man, awesome work!

**Comment by v1ckdesigns** [comment]
thanks :) now it works

**Comment by liiight** [comment]
Any chance you fixing the test so we can merge this? Looks likes a matter of recreating cassette

**Comment by krozer** [comment]
Ok, I'm a beginner with Python and more with travis. From what I understood from the documentation and error, I just have to change the url signin in the cassette. what I did and now all tests are clean.

**Comment by liiight** [comment]
Ideally you delete and recreate the cassette but this works too

**Comment by liiight** [comment]
Thanks for this!

**Comment by busyhobs** [comment]
i have just updated from a relatively old version... and i get the error above. i know very little about programing, even just creating the config script is a challenge. I was using the old imdb lookup using the id and that had been fine but in the new version iys not valid anymore. can anyone shed any light on this. also let me know what info you need from me and how to run debug etc if you need it. flexget runs from cron on my headless server so obviously i only mess with it when it needs updating or breaks in someway.

**Comment by cvium** [comment]
The wiki is a great place to start. https://flexget.com/Plugins/List/imdb_list

Please let old issues lie and use our [forums](https://discuss.flexget.com/) instead if you need help. `imdb_list` is broken.

**Comment by liiight** [comment]
Just use the `imdb_watchlist` plugin instead

**Comment by busyhobs** [comment]
sorry guys, thank you for your help, i was obviously looking in the wrong place. I couldn't be sure if it was broken or i was been stupid, so at least that question is clearedup :)

**Pull request merged**
