### PR TITLE
added channel tags to pushbullet plugin

### PR DESCRIPTION
**Pull request by mingtang**
pushbullet v2 api allows for pushing to custom channels created by users. useful for better organisation of pushes.

### CODE REVIEW

**Comment by nikdoof** [comment]
I don't think this is the best way to add this. ```send_push``` already supports defining the target parameters like it does for device_iden/email

At [line 93](https://github.com/mingtang/Flexget/commit/2f83c08e26ed9262e48cdf10de110139f5c6f4ba#diff-b00f794602b3e7e012db4d8099730078R93) you can call ```self.send_push(task, apikey, title, body, url, channel, 'channel_tag')``` with no further changes to the function.

**Comment by gazpachoking** [comment]
> At line 93 you can call self.send_push(task, apikey, title, body, url, channel, 'channel_tag') with no further changes to the function.

Agreed. @mingtang Mind tweaking this?

**Comment by mingtang** [comment]
Done! Should work as intended now :)

**Comment by gazpachoking** [comment]
Thanks! Can you update the wiki page?

**Comment by mingtang** [comment]
I can't seem to remember my wiki page password. Not sure if I registered my email to my "quaff" account either. Can someone help me out with that?

**Pull request merged**
