### PR TITLE
Support qBittorrent v4.1+, fixes #2522

### LINKED ISSUE #2522: qBittorrent 4.2.0 can't work
Hi
  I've upgrade to qBittorrent 4.2.0 and flexget can't add new tasks to qBittorrent.
  
FlexGet version: 3.0.11
Python version: 3.7.5

### PR DESCRIPTION
**Pull request by pospqsjac**
### Motivation for changes:
Plugin qBittorrent stopped working with qBittorrent v4.2

### Detailed changes:
- Update qBittorrent WebAPIm, [Web API Documentation](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation)

### Addressed issues:
- Fixes #2522

### CODE REVIEW

**Comment by pospqsjac** [comment]
> Are these changes backwards compatible?

No, it supports qBittorrent v4.1.0+ released at 5/05/2018

**Comment by liiight** [comment]
Hmm, that could be a problem. Is there a way to programmetically determine the api version and use the relevant calls?

**Comment by pospqsjac** [comment]
> Hmm, that could be a problem. Is there a way to programmetically determine the api version and use the relevant calls?

Yes, it is possible. I will start working on it.

**Comment by pospqsjac** [comment]
> Hmm, that could be a problem. Is there a way to programmetically determine the api version and use the relevant calls?

Now it supports both versions.

**Comment by liiight** [comment]
Thanks a lot, awesome work on this!

**Pull request merged**
