### PR TITLE
Fix error due to missing 'priority' field default

### PR DESCRIPTION
**Pull request by liiight**
Fix error due to missing 'priority' field default

### CODE REVIEW

**Comment by gazpachoking** [comment]
I think I'd prefer to solve this in the code rather than the schema. 'blank' isn't exactly a default that seems like it should be explicitly set. The schema defaults would be more for a config editor, like what settings would already have values by default.

**Comment by liiight** [comment]
I agree, and i hate setting schema defaults. I much rather set these values via a prepare config method. 
However, I didn't make this plugin, just upgraded it a little. I do however plan to refactor it and add some more missing functionality. 
In the mean time, I think it's worth pushing this as this addresses a crash that my previous pr caused.

**Comment by gazpachoking** [comment]
I mean just change line 69 to `priority = config.get("priority", "")`

**Comment by liiight** [comment]
Yeah, obviously that's the best usage but I chose to remain consistent with the other parameters. 
But whatever, if that's what you want I'll change it.

**Comment by gazpachoking** [comment]
Ahh, I see. You mean the other params are also setting their defaults that way, didn't even look at that. Yeah, I don't care then, it can all be cleaned up later if you want.

**Comment by liiight** [comment]
Yeah, i rather keep consistency for now so the refactor will go smoother.

**Pull request merged**
