### PR TITLE
Allow for multiple ID deletions at once

### PR DESCRIPTION
**Pull request by BrutuZ**
### Motivation for changes:
Making it easier to delete items from an `entry-list` via CLI
### Detailed changes:
- Entry ID is treated as a csv list, so one can delete multiple entries with `flexget entry-list <list-name> <entry-id1>,<entry-id2>,...`
- Title fallback remains unchanged (one entry per run)
### Output:
```
$ flexget entry-list del testy 263527,263556,263557,263558,263590,263591,263778,263779,263780,263781,263782,263815,263848,263977,264010,264043,264231,264294,264295,264513,264762,264950,264982,265169,265232,265233,265345,265346,265360,265361,265362,265363,265364,265365,265366,265367,265368,265369,265649,265873,265906,266100,266165,266230,266245,266406,266471,266504,266505
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
Removing entry `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` from list testy
```

### CODE REVIEW

**Comment by ianstalk** [comment]
It seems a bit weird and messy for one command out of a handful to support comma delimited arguments. I'd consider adding this to the others where it makes sense.

**Comment by liiight** [comment]
This is kinda interesting, but I think it should be handled at the argparse level by allowing sending multiple values to the same param

**Comment by BrutuZ** [comment]
I agree with you both, however expanding the parsing to that level while my original intent, was a few layers beyond my limited knowledge. I stared at `def handle_cli` and `manager.py` for a couple hours and couldn't figure out how, so I tried the "dirty simple" way high up the `entry-list del` level.

Feel free to take this PR as a feature suggestion instead and just close it, I was going to cleanup that list with these dirty changes and go back to using master anyway 👍

**Comment by paranoidi** [comment]
Multiple values seem fine and all, for example kill command takes any number of pids. But using comma makes terminal wizards work really hard. Use spaces so things like $( ... ) work.

**Pull request closed without merging**
